/**
 * DEMO VENDOR DATASET - 50 REALISTIC VENDORS
 * 
 * Comprehensive vendor master data with GST, TDS, MSME, and state permutations
 * for realistic invoice testing and compliance validation.
 * 
 * COVERAGE:
 * - 35 GST Registered, 15 Unregistered
 * - 30 Intra-state (Maharashtra), 20 Inter-state
 * - 20 MSME, 30 Non-MSME
 * - 20 NET15, 30 NET30
 * - 25 TDS Applicable, 25 Non-TDS
 * - 10 Lower TDS Rate vendors
 * - 5 Section 206AB vendors
 */

import { VendorMaster } from './MasterDataContext';

// Indian states for inter-state vendors
const STATES = [
  { name: 'Maharashtra', code: 'MH' },
  { name: 'Karnataka', code: 'KA' },
  { name: 'Tamil Nadu', code: 'TN' },
  { name: 'Gujarat', code: 'GJ' },
  { name: 'Delhi', code: 'DL' },
  { name: 'Rajasthan', code: 'RJ' },
  { name: 'Uttar Pradesh', code: 'UP' },
  { name: 'West Bengal', code: 'WB' },
  { name: 'Telangana', code: 'TS' },
  { name: 'Haryana', code: 'HR' }
];

export const DEMO_VENDOR_DATASET: VendorMaster[] = [
  // ========================================
  // VENDORS 1-10: INTRA-STATE MAHARASHTRA, GST REGISTERED, STANDARD TDS
  // ========================================
  {
    id: 'VEN-DEMO-001',
    code: 'VEN-2001',
    name: 'Mumbai Logistics Solutions',
    legalName: 'Mumbai Logistics Solutions Private Limited',
    pan: 'AABCM1234A',
    gstin: '27AABCM1234A1Z5',
    email: 'billing@mumbailogistics.in',
    phone: '+91 22 2567 8901',
    category: 'Logistics & Transportation',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [{
      id: 'BA-001',
      accountNumber: '001234567890',
      accountName: 'Mumbai Logistics Solutions Pvt Ltd',
      ifscCode: 'HDFC0001234',
      bankName: 'HDFC Bank',
      branchName: 'Nariman Point',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-01-15'
    }],
    addresses: [{
      id: 'ADDR-001',
      type: 'Billing',
      addressLine1: '123 Transport Nagar, Andheri East',
      city: 'Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400069',
      country: 'India',
      gstin: '27AABCM1234A1Z5',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-01-10',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-01-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-002',
    code: 'VEN-2002',
    name: 'Pune Power Equipment Rentals',
    legalName: 'Pune Power Equipment Rentals LLP',
    pan: 'AABCP2345B',
    gstin: '27AABCP2345B1Z1',
    email: 'rentals@punepower.com',
    phone: '+91 20 2678 9012',
    category: 'Equipment Rental',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-567890',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: true,
    tdsSection: '194I',
    bankAccounts: [{
      id: 'BA-002',
      accountNumber: '002345678901',
      accountName: 'Pune Power Equipment Rentals LLP',
      ifscCode: 'ICIC0002345',
      bankName: 'ICICI Bank',
      branchName: 'Pune Camp',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-01-20'
    }],
    addresses: [{
      id: 'ADDR-002',
      type: 'Billing',
      addressLine1: 'Plot 45, Pimpri Industrial Area',
      city: 'Pune',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '411018',
      country: 'India',
      gstin: '27AABCP2345B1Z1',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-01-15',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-01-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-003',
    code: 'VEN-2003',
    name: 'Nashik Food Distributors',
    legalName: 'Nashik Food Distributors India Private Limited',
    pan: 'AABCN3456C',
    gstin: '27AABCN3456C1Z2',
    email: 'orders@nashikfood.in',
    phone: '+91 253 234 5678',
    category: 'Food & Beverage Suppliers',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-678901',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-003',
      accountNumber: '003456789012',
      accountName: 'Nashik Food Distributors India Pvt Ltd',
      ifscCode: 'SBIN0003456',
      bankName: 'State Bank of India',
      branchName: 'Nashik Road',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-02-01'
    }],
    addresses: [{
      id: 'ADDR-003',
      type: 'Billing',
      addressLine1: 'Warehouse 12, MIDC Area',
      city: 'Nashik',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '422010',
      country: 'India',
      gstin: '27AABCN3456C1Z2',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-01-20',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-01-22',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-004',
    code: 'VEN-2004',
    name: 'Thane Security Services',
    legalName: 'Thane Security Services Private Limited',
    pan: 'AABCT4567D',
    gstin: '27AABCT4567D1Z3',
    email: 'security@thanesec.in',
    phone: '+91 22 2589 6789',
    category: 'Security Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    bankAccounts: [{
      id: 'BA-004',
      accountNumber: '004567890123',
      accountName: 'Thane Security Services Pvt Ltd',
      ifscCode: 'HDFC0004567',
      bankName: 'HDFC Bank',
      branchName: 'Thane West',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-02-05'
    }],
    addresses: [{
      id: 'ADDR-004',
      type: 'Billing',
      addressLine1: 'Office 301, Manpada Complex',
      city: 'Thane',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400610',
      country: 'India',
      gstin: '27AABCT4567D1Z3',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-02-01',
    approvedBy: 'Operations Head',
    approvedDate: '2024-02-03',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-005',
    code: 'VEN-2005',
    name: 'Nagpur Construction Materials',
    legalName: 'Nagpur Construction Materials LLP',
    pan: 'AABCN5678E',
    gstin: '27AABCN5678E1Z4',
    email: 'sales@nagpurconst.in',
    phone: '+91 712 256 7890',
    category: 'Construction & Building Materials',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-789012',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-005',
      accountNumber: '005678901234',
      accountName: 'Nagpur Construction Materials LLP',
      ifscCode: 'ICIC0005678',
      bankName: 'ICICI Bank',
      branchName: 'Sitabuldi',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-02-10'
    }],
    addresses: [{
      id: 'ADDR-005',
      type: 'Billing',
      addressLine1: 'Plot 78, Kalmeshwar Road',
      city: 'Nagpur',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '440026',
      country: 'India',
      gstin: '27AABCN5678E1Z4',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-02-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-02-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-006',
    code: 'VEN-2006',
    name: 'Mumbai IT Consulting Group',
    legalName: 'Mumbai IT Consulting Group Private Limited',
    pan: 'AABCM6789F',
    gstin: '27AABCM6789F1Z5',
    email: 'projects@mumbaiit.com',
    phone: '+91 22 4567 8901',
    category: 'IT Services & Consulting',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    lowerTdsApplicable: true,
    lowerTdsRate: 2,
    lowerTdsReference: 'LDC-2025-001',
    bankAccounts: [{
      id: 'BA-006',
      accountNumber: '006789012345',
      accountName: 'Mumbai IT Consulting Group Pvt Ltd',
      ifscCode: 'SBIN0006789',
      bankName: 'State Bank of India',
      branchName: 'BKC',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-02-15'
    }],
    addresses: [{
      id: 'ADDR-006',
      type: 'Billing',
      addressLine1: 'Tower 3, Bandra Kurla Complex',
      city: 'Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400051',
      country: 'India',
      gstin: '27AABCM6789F1Z5',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-02-10',
    approvedBy: 'IT Head',
    approvedDate: '2024-02-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-007',
    code: 'VEN-2007',
    name: 'Aurangabad Packaging Solutions',
    legalName: 'Aurangabad Packaging Solutions India Pvt Ltd',
    pan: 'AABCA7890G',
    gstin: '27AABCA7890G1Z6',
    email: 'info@aurangabadpack.in',
    phone: '+91 240 234 5678',
    category: 'Packaging Materials',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-890123',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-007',
      accountNumber: '007890123456',
      accountName: 'Aurangabad Packaging Solutions India Pvt Ltd',
      ifscCode: 'HDFC0007890',
      bankName: 'HDFC Bank',
      branchName: 'Aurangabad',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-02-20'
    }],
    addresses: [{
      id: 'ADDR-007',
      type: 'Billing',
      addressLine1: 'Unit 23, Chikalthana MIDC',
      city: 'Aurangabad',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '431210',
      country: 'India',
      gstin: '27AABCA7890G1Z6',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-02-15',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-02-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-008',
    code: 'VEN-2008',
    name: 'Kalyan Cleaning & Housekeeping',
    legalName: 'Kalyan Cleaning & Housekeeping Services LLP',
    pan: 'AABCK8901H',
    gstin: '27AABCK8901H1Z7',
    email: 'contact@kalyancleaning.in',
    phone: '+91 251 234 5678',
    category: 'Facility Management',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    lowerTdsApplicable: true,
    lowerTdsRate: 0.5,
    lowerTdsReference: 'LDC-2025-002',
    bankAccounts: [{
      id: 'BA-008',
      accountNumber: '008901234567',
      accountName: 'Kalyan Cleaning & Housekeeping Services LLP',
      ifscCode: 'ICIC0008901',
      bankName: 'ICICI Bank',
      branchName: 'Kalyan East',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-02-25'
    }],
    addresses: [{
      id: 'ADDR-008',
      type: 'Billing',
      addressLine1: 'Shop 45, Bazarpeth',
      city: 'Kalyan',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '421301',
      country: 'India',
      gstin: '27AABCK8901H1Z7',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-02-20',
    approvedBy: 'Operations Head',
    approvedDate: '2024-02-22',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-009',
    code: 'VEN-2009',
    name: 'Navi Mumbai Electrical Services',
    legalName: 'Navi Mumbai Electrical Services Private Limited',
    pan: 'AABCN9012I',
    gstin: '27AABCN9012I1Z8',
    email: 'electrical@navimumbai.in',
    phone: '+91 22 2789 0123',
    category: 'Electrical & Maintenance',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-901234',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [{
      id: 'BA-009',
      accountNumber: '009012345678',
      accountName: 'Navi Mumbai Electrical Services Pvt Ltd',
      ifscCode: 'SBIN0009012',
      bankName: 'State Bank of India',
      branchName: 'Vashi',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-03-01'
    }],
    addresses: [{
      id: 'ADDR-009',
      type: 'Billing',
      addressLine1: 'Plot 12, Sector 11, Vashi',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400703',
      country: 'India',
      gstin: '27AABCN9012I1Z8',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-02-25',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-02-28',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-010',
    code: 'VEN-2010',
    name: 'Pune Office Supplies Hub',
    legalName: 'Pune Office Supplies Hub LLP',
    pan: 'AABCP0123J',
    gstin: '27AABCP0123J1Z9',
    email: 'orders@puneoffice.in',
    phone: '+91 20 2590 1234',
    category: 'Office Supplies & Stationery',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-010',
      accountNumber: '010123456789',
      accountName: 'Pune Office Supplies Hub LLP',
      ifscCode: 'HDFC0010123',
      bankName: 'HDFC Bank',
      branchName: 'Shivajinagar',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-03-05'
    }],
    addresses: [{
      id: 'ADDR-010',
      type: 'Billing',
      addressLine1: 'Shop 67, FC Road',
      city: 'Pune',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '411004',
      country: 'India',
      gstin: '27AABCP0123J1Z9',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-03-01',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-03-03',
    entityId: 'ENT-PROCINIX-IN'
  },

  // ========================================
  // VENDORS 11-20: INTER-STATE, GST REGISTERED, TDS MIX
  // ========================================
  {
    id: 'VEN-DEMO-011',
    code: 'VEN-2011',
    name: 'Bangalore Tech Solutions',
    legalName: 'Bangalore Tech Solutions Private Limited',
    pan: 'AABCB1234K',
    gstin: '29AABCB1234K1Z1',
    email: 'tech@bangaloretech.in',
    phone: '+91 80 4123 4567',
    category: 'IT Services & Consulting',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    section206ABApplicable: true,
    effectiveTdsRate: 20, // 194J standard 10% × 2
    bankAccounts: [{
      id: 'BA-011',
      accountNumber: '011234567890',
      accountName: 'Bangalore Tech Solutions Pvt Ltd',
      ifscCode: 'ICIC0011234',
      bankName: 'ICICI Bank',
      branchName: 'Koramangala',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-03-10'
    }],
    addresses: [{
      id: 'ADDR-011',
      type: 'Billing',
      addressLine1: 'Tower B, Outer Ring Road',
      city: 'Bangalore',
      state: 'Karnataka',
      stateCode: 'KA',
      pincode: '560034',
      country: 'India',
      gstin: '29AABCB1234K1Z1',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-03-05',
    approvedBy: 'IT Head',
    approvedDate: '2024-03-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-012',
    code: 'VEN-2012',
    name: 'Chennai Logistics Express',
    legalName: 'Chennai Logistics Express India Pvt Ltd',
    pan: 'AABCC2345L',
    gstin: '33AABCC2345L1Z2',
    email: 'dispatch@chennailogistics.in',
    phone: '+91 44 2345 6789',
    category: 'Logistics & Transportation',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-TN-33-123456',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [{
      id: 'BA-012',
      accountNumber: '012345678901',
      accountName: 'Chennai Logistics Express India Pvt Ltd',
      ifscCode: 'SBIN0012345',
      bankName: 'State Bank of India',
      branchName: 'T Nagar',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-03-15'
    }],
    addresses: [{
      id: 'ADDR-012',
      type: 'Billing',
      addressLine1: 'Warehouse 45, Ambattur Industrial Estate',
      city: 'Chennai',
      state: 'Tamil Nadu',
      stateCode: 'TN',
      pincode: '600058',
      country: 'India',
      gstin: '33AABCC2345L1Z2',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-03-10',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-03-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-013',
    code: 'VEN-2013',
    name: 'Ahmedabad Food Processors',
    legalName: 'Ahmedabad Food Processors LLP',
    pan: 'AABCA3456M',
    gstin: '24AABCA3456M1Z3',
    email: 'sales@ahmedabadfood.in',
    phone: '+91 79 2456 7890',
    category: 'Food & Beverage Suppliers',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-013',
      accountNumber: '013456789012',
      accountName: 'Ahmedabad Food Processors LLP',
      ifscCode: 'HDFC0013456',
      bankName: 'HDFC Bank',
      branchName: 'Satellite',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-03-20'
    }],
    addresses: [{
      id: 'ADDR-013',
      type: 'Billing',
      addressLine1: 'Plot 78, Naroda GIDC',
      city: 'Ahmedabad',
      state: 'Gujarat',
      stateCode: 'GJ',
      pincode: '382330',
      country: 'India',
      gstin: '24AABCA3456M1Z3',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-03-15',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-03-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-014',
    code: 'VEN-2014',
    name: 'Delhi Property Rentals',
    legalName: 'Delhi Property Rentals Private Limited',
    pan: 'AABCD4567N',
    gstin: '07AABCD4567N1Z4',
    email: 'leasing@delhiproperty.in',
    phone: '+91 11 2567 8901',
    category: 'Real Estate & Rentals',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194I',
    lowerTdsApplicable: true,
    lowerTdsRate: 2,
    lowerTdsReference: 'LDC-2025-003',
    bankAccounts: [{
      id: 'BA-014',
      accountNumber: '014567890123',
      accountName: 'Delhi Property Rentals Pvt Ltd',
      ifscCode: 'ICIC0014567',
      bankName: 'ICICI Bank',
      branchName: 'Connaught Place',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-03-25'
    }],
    addresses: [{
      id: 'ADDR-014',
      type: 'Billing',
      addressLine1: 'Block B, Connaught Circus',
      city: 'New Delhi',
      state: 'Delhi',
      stateCode: 'DL',
      pincode: '110001',
      country: 'India',
      gstin: '07AABCD4567N1Z4',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-03-20',
    approvedBy: 'Finance Head',
    approvedDate: '2024-03-22',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-015',
    code: 'VEN-2015',
    name: 'Jaipur Textile Traders',
    legalName: 'Jaipur Textile Traders India LLP',
    pan: 'AABCJ5678O',
    gstin: '08AABCJ5678O1Z5',
    email: 'textiles@jaipurtextile.in',
    phone: '+91 141 234 5678',
    category: 'Textiles & Fabrics',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-RJ-08-234567',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-015',
      accountNumber: '015678901234',
      accountName: 'Jaipur Textile Traders India LLP',
      ifscCode: 'SBIN0015678',
      bankName: 'State Bank of India',
      branchName: 'MI Road',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-04-01'
    }],
    addresses: [{
      id: 'ADDR-015',
      type: 'Billing',
      addressLine1: 'Shop 23, Johari Bazaar',
      city: 'Jaipur',
      state: 'Rajasthan',
      stateCode: 'RJ',
      pincode: '302003',
      country: 'India',
      gstin: '08AABCJ5678O1Z5',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-03-25',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-03-28',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-016',
    code: 'VEN-2016',
    name: 'Hyderabad Engineering Works',
    legalName: 'Hyderabad Engineering Works Private Limited',
    pan: 'AABCH6789P',
    gstin: '36AABCH6789P1Z6',
    email: 'engineering@hyderabadworks.in',
    phone: '+91 40 2345 6789',
    category: 'Engineering & Manufacturing',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    section206ABApplicable: true,
    effectiveTdsRate: 4, // 194C standard 1% + 2% = 3%, but max(1*2, 1+2) = 3%
    bankAccounts: [{
      id: 'BA-016',
      accountNumber: '016789012345',
      accountName: 'Hyderabad Engineering Works Pvt Ltd',
      ifscCode: 'HDFC0016789',
      bankName: 'HDFC Bank',
      branchName: 'Somajiguda',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-04-05'
    }],
    addresses: [{
      id: 'ADDR-016',
      type: 'Billing',
      addressLine1: 'Plot 156, IDA Jeedimetla',
      city: 'Hyderabad',
      state: 'Telangana',
      stateCode: 'TS',
      pincode: '500055',
      country: 'India',
      gstin: '36AABCH6789P1Z6',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-04-01',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-04-03',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-017',
    code: 'VEN-2017',
    name: 'Kolkata Printing Press',
    legalName: 'Kolkata Printing Press LLP',
    pan: 'AABCK7890Q',
    gstin: '19AABCK7890Q1Z7',
    email: 'printing@kolkatapress.in',
    phone: '+91 33 2456 7890',
    category: 'Printing & Publishing',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-WB-19-345678',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-017',
      accountNumber: '017890123456',
      accountName: 'Kolkata Printing Press LLP',
      ifscCode: 'ICIC0017890',
      bankName: 'ICICI Bank',
      branchName: 'Park Street',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-04-10'
    }],
    addresses: [{
      id: 'ADDR-017',
      type: 'Billing',
      addressLine1: '45 College Street',
      city: 'Kolkata',
      state: 'West Bengal',
      stateCode: 'WB',
      pincode: '700073',
      country: 'India',
      gstin: '19AABCK7890Q1Z7',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-04-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-04-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-018',
    code: 'VEN-2018',
    name: 'Lucknow Facility Management',
    legalName: 'Lucknow Facility Management Services Pvt Ltd',
    pan: 'AABCL8901R',
    gstin: '09AABCL8901R1Z8',
    email: 'services@lucknowfacility.in',
    phone: '+91 522 234 5678',
    category: 'Facility Management',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    lowerTdsApplicable: true,
    lowerTdsRate: 2,
    lowerTdsReference: 'LDC-2025-004',
    bankAccounts: [{
      id: 'BA-018',
      accountNumber: '018901234567',
      accountName: 'Lucknow Facility Management Services Pvt Ltd',
      ifscCode: 'SBIN0018901',
      bankName: 'State Bank of India',
      branchName: 'Hazratganj',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-04-15'
    }],
    addresses: [{
      id: 'ADDR-018',
      type: 'Billing',
      addressLine1: 'Office 12, Gomti Nagar',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      stateCode: 'UP',
      pincode: '226010',
      country: 'India',
      gstin: '09AABCL8901R1Z8',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-04-10',
    approvedBy: 'Operations Head',
    approvedDate: '2024-04-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-019',
    code: 'VEN-2019',
    name: 'Gurgaon HR Consultants',
    legalName: 'Gurgaon HR Consultants India Private Limited',
    pan: 'AABCG9012S',
    gstin: '06AABCG9012S1Z9',
    email: 'hr@gurgaonhr.in',
    phone: '+91 124 234 5678',
    category: 'HR & Recruitment Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    section206ABApplicable: true,
    effectiveTdsRate: 20,
    bankAccounts: [{
      id: 'BA-019',
      accountNumber: '019012345678',
      accountName: 'Gurgaon HR Consultants India Pvt Ltd',
      ifscCode: 'HDFC0019012',
      bankName: 'HDFC Bank',
      branchName: 'Cyber City',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-04-20'
    }],
    addresses: [{
      id: 'ADDR-019',
      type: 'Billing',
      addressLine1: 'Tower 4, DLF Cyber City',
      city: 'Gurgaon',
      state: 'Haryana',
      stateCode: 'HR',
      pincode: '122002',
      country: 'India',
      gstin: '06AABCG9012S1Z9',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-04-15',
    approvedBy: 'HR Head',
    approvedDate: '2024-04-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-020',
    code: 'VEN-2020',
    name: 'Surat Diamond Tools',
    legalName: 'Surat Diamond Tools Manufacturing LLP',
    pan: 'AABCS0123T',
    gstin: '24AABCS0123T1Z0',
    email: 'sales@suratdiamond.in',
    phone: '+91 261 234 5678',
    category: 'Industrial Tools & Equipment',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-GJ-24-456789',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-020',
      accountNumber: '020123456789',
      accountName: 'Surat Diamond Tools Manufacturing LLP',
      ifscCode: 'ICIC0020123',
      bankName: 'ICICI Bank',
      branchName: 'Ring Road',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-04-25'
    }],
    addresses: [{
      id: 'ADDR-020',
      type: 'Billing',
      addressLine1: 'Plot 89, Sachin GIDC',
      city: 'Surat',
      state: 'Gujarat',
      stateCode: 'GJ',
      pincode: '394230',
      country: 'India',
      gstin: '24AABCS0123T1Z0',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-04-20',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-04-22',
    entityId: 'ENT-PROCINIX-IN'
  },

  // ========================================
  // VENDORS 21-30: INTRA-STATE MAHARASHTRA, MIXED GST STATUS, LOWER TDS
  // ========================================
  {
    id: 'VEN-DEMO-021',
    code: 'VEN-2021',
    name: 'Mumbai Catering Services',
    legalName: 'Mumbai Catering Services Private Limited',
    pan: 'AABCM1234U',
    gstin: '27AABCM1234U1Z1',
    email: 'catering@mumbaicatering.in',
    phone: '+91 22 2678 9012',
    category: 'Catering & Food Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    lowerTdsApplicable: true,
    lowerTdsRate: 0.5,
    lowerTdsReference: 'LDC-2025-005',
    bankAccounts: [{
      id: 'BA-021',
      accountNumber: '021234567890',
      accountName: 'Mumbai Catering Services Pvt Ltd',
      ifscCode: 'SBIN0021234',
      bankName: 'State Bank of India',
      branchName: 'Dadar',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-05-01'
    }],
    addresses: [{
      id: 'ADDR-021',
      type: 'Billing',
      addressLine1: 'Shop 34, Dadar Market',
      city: 'Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400014',
      country: 'India',
      gstin: '27AABCM1234U1Z1',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-04-25',
    approvedBy: 'Admin',
    approvedDate: '2024-04-28',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-022',
    code: 'VEN-2022',
    name: 'Pune Water Suppliers',
    legalName: 'Pune Water Suppliers LLP',
    pan: 'AABCP2345V',
    gstin: '', // UNREGISTERED
    email: 'water@punewater.in',
    phone: '+91 20 2789 0123',
    category: 'Utilities & Water Supply',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-567890',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-022',
      accountNumber: '022345678901',
      accountName: 'Pune Water Suppliers LLP',
      ifscCode: 'HDFC0022345',
      bankName: 'HDFC Bank',
      branchName: 'Kothrud',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-05-05'
    }],
    addresses: [{
      id: 'ADDR-022',
      type: 'Billing',
      addressLine1: 'Lane 5, Kothrud',
      city: 'Pune',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '411038',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-05-01',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-05-03',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-023',
    code: 'VEN-2023',
    name: 'Nashik Transport Corporation',
    legalName: 'Nashik Transport Corporation Pvt Ltd',
    pan: 'AABCN3456W',
    gstin: '27AABCN3456W1Z2',
    email: 'transport@nashiktc.in',
    phone: '+91 253 234 5678',
    category: 'Logistics & Transportation',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    lowerTdsApplicable: true,
    lowerTdsRate: 0.5,
    lowerTdsReference: 'LDC-2025-006',
    bankAccounts: [{
      id: 'BA-023',
      accountNumber: '023456789012',
      accountName: 'Nashik Transport Corporation Pvt Ltd',
      ifscCode: 'ICIC0023456',
      bankName: 'ICICI Bank',
      branchName: 'Nashik Main',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-05-10'
    }],
    addresses: [{
      id: 'ADDR-023',
      type: 'Billing',
      addressLine1: 'Transport Hub, Mumbai Naka',
      city: 'Nashik',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '422001',
      country: 'India',
      gstin: '27AABCN3456W1Z2',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-05-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-05-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-024',
    code: 'VEN-2024',
    name: 'Thane Legal Advisors',
    legalName: 'Thane Legal Advisors LLP',
    pan: 'AABCT4567X',
    gstin: '27AABCT4567X1Z3',
    email: 'legal@thanelegal.in',
    phone: '+91 22 2590 1234',
    category: 'Legal & Professional Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    lowerTdsApplicable: true,
    lowerTdsRate: 2,
    lowerTdsReference: 'LDC-2025-007',
    bankAccounts: [{
      id: 'BA-024',
      accountNumber: '024567890123',
      accountName: 'Thane Legal Advisors LLP',
      ifscCode: 'SBIN0024567',
      bankName: 'State Bank of India',
      branchName: 'Thane East',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-05-15'
    }],
    addresses: [{
      id: 'ADDR-024',
      type: 'Billing',
      addressLine1: 'Chamber 12, Court Road',
      city: 'Thane',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400601',
      country: 'India',
      gstin: '27AABCT4567X1Z3',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-05-10',
    approvedBy: 'Legal Head',
    approvedDate: '2024-05-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-025',
    code: 'VEN-2025',
    name: 'Nagpur Furniture Mart',
    legalName: 'Nagpur Furniture Mart India Pvt Ltd',
    pan: 'AABCN5678Y',
    gstin: '', // UNREGISTERED
    email: 'furniture@nagpurmart.in',
    phone: '+91 712 234 5678',
    category: 'Furniture & Fixtures',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-678901',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-025',
      accountNumber: '025678901234',
      accountName: 'Nagpur Furniture Mart India Pvt Ltd',
      ifscCode: 'HDFC0025678',
      bankName: 'HDFC Bank',
      branchName: 'Dharampeth',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-05-20'
    }],
    addresses: [{
      id: 'ADDR-025',
      type: 'Billing',
      addressLine1: 'Shop 67, Dharampeth',
      city: 'Nagpur',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '440010',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-05-15',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-05-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-026',
    code: 'VEN-2026',
    name: 'Mumbai Digital Marketing',
    legalName: 'Mumbai Digital Marketing Services Pvt Ltd',
    pan: 'AABCM6789Z',
    gstin: '27AABCM6789Z1Z4',
    email: 'marketing@mumbaidigital.in',
    phone: '+91 22 4123 4567',
    category: 'Marketing & Advertising',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    section206ABApplicable: true,
    effectiveTdsRate: 20,
    bankAccounts: [{
      id: 'BA-026',
      accountNumber: '026789012345',
      accountName: 'Mumbai Digital Marketing Services Pvt Ltd',
      ifscCode: 'ICIC0026789',
      bankName: 'ICICI Bank',
      branchName: 'Lower Parel',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-05-25'
    }],
    addresses: [{
      id: 'ADDR-026',
      type: 'Billing',
      addressLine1: 'Tower 5, Lower Parel',
      city: 'Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400013',
      country: 'India',
      gstin: '27AABCM6789Z1Z4',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-05-20',
    approvedBy: 'Marketing Head',
    approvedDate: '2024-05-22',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-027',
    code: 'VEN-2027',
    name: 'Aurangabad Hardware Store',
    legalName: 'Aurangabad Hardware Store LLP',
    pan: 'AABCA7890A',
    gstin: '27AABCA7890A1Z5',
    email: 'hardware@aurangabadhw.in',
    phone: '+91 240 234 5678',
    category: 'Hardware & Building Materials',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-789012',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-027',
      accountNumber: '027890123456',
      accountName: 'Aurangabad Hardware Store LLP',
      ifscCode: 'SBIN0027890',
      bankName: 'State Bank of India',
      branchName: 'Aurangabad Central',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-06-01'
    }],
    addresses: [{
      id: 'ADDR-027',
      type: 'Billing',
      addressLine1: 'Main Market, Station Road',
      city: 'Aurangabad',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '431001',
      country: 'India',
      gstin: '27AABCA7890A1Z5',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-05-25',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-05-28',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-028',
    code: 'VEN-2028',
    name: 'Kalyan Event Management',
    legalName: 'Kalyan Event Management Services Pvt Ltd',
    pan: 'AABCK8901B',
    gstin: '', // UNREGISTERED
    email: 'events@kalyanevent.in',
    phone: '+91 251 234 5678',
    category: 'Event Management Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [{
      id: 'BA-028',
      accountNumber: '028901234567',
      accountName: 'Kalyan Event Management Services Pvt Ltd',
      ifscCode: 'HDFC0028901',
      bankName: 'HDFC Bank',
      branchName: 'Kalyan West',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-06-05'
    }],
    addresses: [{
      id: 'ADDR-028',
      type: 'Billing',
      addressLine1: 'Office 12, Khadakpada',
      city: 'Kalyan',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '421301',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-06-01',
    approvedBy: 'Admin',
    approvedDate: '2024-06-03',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-029',
    code: 'VEN-2029',
    name: 'Navi Mumbai HVAC Solutions',
    legalName: 'Navi Mumbai HVAC Solutions Pvt Ltd',
    pan: 'AABCN9012C',
    gstin: '27AABCN9012C1Z6',
    email: 'hvac@navimumbaihvac.in',
    phone: '+91 22 2701 2345',
    category: 'HVAC & Climate Control',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    lowerTdsApplicable: true,
    lowerTdsRate: 0.5,
    lowerTdsReference: 'LDC-2025-008',
    bankAccounts: [{
      id: 'BA-029',
      accountNumber: '029012345678',
      accountName: 'Navi Mumbai HVAC Solutions Pvt Ltd',
      ifscCode: 'ICIC0029012',
      bankName: 'ICICI Bank',
      branchName: 'Nerul',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-06-10'
    }],
    addresses: [{
      id: 'ADDR-029',
      type: 'Billing',
      addressLine1: 'Sector 19, Nerul',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400706',
      country: 'India',
      gstin: '27AABCN9012C1Z6',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-06-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-06-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-030',
    code: 'VEN-2030',
    name: 'Pune Automotive Parts',
    legalName: 'Pune Automotive Parts Manufacturing LLP',
    pan: 'AABCP0123D',
    gstin: '27AABCP0123D1Z7',
    email: 'auto@puneauto.in',
    phone: '+91 20 2612 3456',
    category: 'Automotive Parts & Accessories',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-890123',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-030',
      accountNumber: '030123456789',
      accountName: 'Pune Automotive Parts Manufacturing LLP',
      ifscCode: 'SBIN0030123',
      bankName: 'State Bank of India',
      branchName: 'Chakan',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-06-15'
    }],
    addresses: [{
      id: 'ADDR-030',
      type: 'Billing',
      addressLine1: 'Plot 156, Chakan Industrial Area',
      city: 'Pune',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '410501',
      country: 'India',
      gstin: '27AABCP0123D1Z7',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-06-10',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-06-12',
    entityId: 'ENT-PROCINIX-IN'
  },

  // ========================================
  // VENDORS 31-40: INTER-STATE, MIXED GST, SECTION 206AB
  // ========================================
  {
    id: 'VEN-DEMO-031',
    code: 'VEN-2031',
    name: 'Bangalore Software Labs',
    legalName: 'Bangalore Software Labs Private Limited',
    pan: 'AABCB1234E',
    gstin: '29AABCB1234E1Z8',
    email: 'software@bangalorelab.in',
    phone: '+91 80 2345 6789',
    category: 'Software Development',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    lowerTdsApplicable: true,
    lowerTdsRate: 2,
    lowerTdsReference: 'LDC-2025-009',
    bankAccounts: [{
      id: 'BA-031',
      accountNumber: '031234567890',
      accountName: 'Bangalore Software Labs Pvt Ltd',
      ifscCode: 'HDFC0031234',
      bankName: 'HDFC Bank',
      branchName: 'Indiranagar',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-06-20'
    }],
    addresses: [{
      id: 'ADDR-031',
      type: 'Billing',
      addressLine1: 'Tech Park, Whitefield',
      city: 'Bangalore',
      state: 'Karnataka',
      stateCode: 'KA',
      pincode: '560066',
      country: 'India',
      gstin: '29AABCB1234E1Z8',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-06-15',
    approvedBy: 'IT Head',
    approvedDate: '2024-06-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-032',
    code: 'VEN-2032',
    name: 'Chennai Electrical Components',
    legalName: 'Chennai Electrical Components Pvt Ltd',
    pan: 'AABCC2345F',
    gstin: '', // UNREGISTERED
    email: 'electrical@chennaicomp.in',
    phone: '+91 44 2456 7890',
    category: 'Electrical Components',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-TN-33-234567',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-032',
      accountNumber: '032345678901',
      accountName: 'Chennai Electrical Components Pvt Ltd',
      ifscCode: 'ICIC0032345',
      bankName: 'ICICI Bank',
      branchName: 'Anna Nagar',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-06-25'
    }],
    addresses: [{
      id: 'ADDR-032',
      type: 'Billing',
      addressLine1: 'Shop 34, Ritchie Street',
      city: 'Chennai',
      state: 'Tamil Nadu',
      stateCode: 'TN',
      pincode: '600002',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-06-20',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-06-22',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-033',
    code: 'VEN-2033',
    name: 'Ahmedabad Export House',
    legalName: 'Ahmedabad Export House LLP',
    pan: 'AABCA3456G',
    gstin: '24AABCA3456G1Z9',
    email: 'export@ahmedabadhouse.in',
    phone: '+91 79 2567 8901',
    category: 'Import-Export Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [{
      id: 'BA-033',
      accountNumber: '033456789012',
      accountName: 'Ahmedabad Export House LLP',
      ifscCode: 'SBIN0033456',
      bankName: 'State Bank of India',
      branchName: 'Ashram Road',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-07-01'
    }],
    addresses: [{
      id: 'ADDR-033',
      type: 'Billing',
      addressLine1: 'Trade Centre, Ashram Road',
      city: 'Ahmedabad',
      state: 'Gujarat',
      stateCode: 'GJ',
      pincode: '380009',
      country: 'India',
      gstin: '24AABCA3456G1Z9',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-06-25',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-06-28',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-034',
    code: 'VEN-2034',
    name: 'Delhi Commercial Properties',
    legalName: 'Delhi Commercial Properties India Pvt Ltd',
    pan: 'AABCD4567H',
    gstin: '07AABCD4567H1Z0',
    email: 'properties@delhicommercial.in',
    phone: '+91 11 2678 9012',
    category: 'Real Estate & Rentals',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194I',
    section206ABApplicable: true,
    effectiveTdsRate: 20,
    bankAccounts: [{
      id: 'BA-034',
      accountNumber: '034567890123',
      accountName: 'Delhi Commercial Properties India Pvt Ltd',
      ifscCode: 'HDFC0034567',
      bankName: 'HDFC Bank',
      branchName: 'Nehru Place',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-07-05'
    }],
    addresses: [{
      id: 'ADDR-034',
      type: 'Billing',
      addressLine1: 'Tower 3, Nehru Place',
      city: 'New Delhi',
      state: 'Delhi',
      stateCode: 'DL',
      pincode: '110019',
      country: 'India',
      gstin: '07AABCD4567H1Z0',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-07-01',
    approvedBy: 'Finance Head',
    approvedDate: '2024-07-03',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-035',
    code: 'VEN-2035',
    name: 'Jaipur Handicrafts Exporters',
    legalName: 'Jaipur Handicrafts Exporters LLP',
    pan: 'AABCJ5678I',
    gstin: '', // UNREGISTERED
    email: 'handicrafts@jaipurexport.in',
    phone: '+91 141 234 5678',
    category: 'Handicrafts & Artifacts',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-RJ-08-345678',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-035',
      accountNumber: '035678901234',
      accountName: 'Jaipur Handicrafts Exporters LLP',
      ifscCode: 'ICIC0035678',
      bankName: 'ICICI Bank',
      branchName: 'Johri Bazaar',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-07-10'
    }],
    addresses: [{
      id: 'ADDR-035',
      type: 'Billing',
      addressLine1: 'Shop 89, Johri Bazaar',
      city: 'Jaipur',
      state: 'Rajasthan',
      stateCode: 'RJ',
      pincode: '302003',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-07-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-07-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-036',
    code: 'VEN-2036',
    name: 'Hyderabad Pharmaceutical Supplies',
    legalName: 'Hyderabad Pharmaceutical Supplies Pvt Ltd',
    pan: 'AABCH6789J',
    gstin: '36AABCH6789J1Z1',
    email: 'pharma@hyderabadsupplies.in',
    phone: '+91 40 2789 0123',
    category: 'Pharmaceutical Supplies',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-036',
      accountNumber: '036789012345',
      accountName: 'Hyderabad Pharmaceutical Supplies Pvt Ltd',
      ifscCode: 'SBIN0036789',
      bankName: 'State Bank of India',
      branchName: 'Banjara Hills',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-07-15'
    }],
    addresses: [{
      id: 'ADDR-036',
      type: 'Billing',
      addressLine1: 'Plot 234, IDA Pashamylaram',
      city: 'Hyderabad',
      state: 'Telangana',
      stateCode: 'TS',
      pincode: '502307',
      country: 'India',
      gstin: '36AABCH6789J1Z1',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-07-10',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-07-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-037',
    code: 'VEN-2037',
    name: 'Kolkata Trading Company',
    legalName: 'Kolkata Trading Company LLP',
    pan: 'AABCK7890K',
    gstin: '19AABCK7890K1Z2',
    email: 'trading@kolkatatrade.in',
    phone: '+91 33 2890 1234',
    category: 'General Trading',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-WB-19-456789',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-037',
      accountNumber: '037890123456',
      accountName: 'Kolkata Trading Company LLP',
      ifscCode: 'HDFC0037890',
      bankName: 'HDFC Bank',
      branchName: 'Esplanade',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-07-20'
    }],
    addresses: [{
      id: 'ADDR-037',
      type: 'Billing',
      addressLine1: '67 Dalhousie Square',
      city: 'Kolkata',
      state: 'West Bengal',
      stateCode: 'WB',
      pincode: '700001',
      country: 'India',
      gstin: '19AABCK7890K1Z2',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-07-15',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-07-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-038',
    code: 'VEN-2038',
    name: 'Lucknow Training Academy',
    legalName: 'Lucknow Training Academy Pvt Ltd',
    pan: 'AABCL8901L',
    gstin: '', // UNREGISTERED
    email: 'training@lucknowacademy.in',
    phone: '+91 522 234 5678',
    category: 'Training & Education Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    lowerTdsApplicable: true,
    lowerTdsRate: 2,
    lowerTdsReference: 'LDC-2025-010',
    bankAccounts: [{
      id: 'BA-038',
      accountNumber: '038901234567',
      accountName: 'Lucknow Training Academy Pvt Ltd',
      ifscCode: 'ICIC0038901',
      bankName: 'ICICI Bank',
      branchName: 'Aminabad',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-07-25'
    }],
    addresses: [{
      id: 'ADDR-038',
      type: 'Billing',
      addressLine1: 'Building 23, Gomti Nagar Extension',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      stateCode: 'UP',
      pincode: '226010',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-07-20',
    approvedBy: 'HR Head',
    approvedDate: '2024-07-22',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-039',
    code: 'VEN-2039',
    name: 'Gurgaon Data Center Services',
    legalName: 'Gurgaon Data Center Services India Pvt Ltd',
    pan: 'AABCG9012M',
    gstin: '06AABCG9012M1Z3',
    email: 'datacenter@gurgaondc.in',
    phone: '+91 124 234 5678',
    category: 'Data Center & Cloud Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    bankAccounts: [{
      id: 'BA-039',
      accountNumber: '039012345678',
      accountName: 'Gurgaon Data Center Services India Pvt Ltd',
      ifscCode: 'SBIN0039012',
      bankName: 'State Bank of India',
      branchName: 'Udyog Vihar',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-08-01'
    }],
    addresses: [{
      id: 'ADDR-039',
      type: 'Billing',
      addressLine1: 'Tower 8, Udyog Vihar Phase 4',
      city: 'Gurgaon',
      state: 'Haryana',
      stateCode: 'HR',
      pincode: '122015',
      country: 'India',
      gstin: '06AABCG9012M1Z3',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-07-25',
    approvedBy: 'IT Head',
    approvedDate: '2024-07-28',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-040',
    code: 'VEN-2040',
    name: 'Surat Chemical Industries',
    legalName: 'Surat Chemical Industries LLP',
    pan: 'AABCS0123N',
    gstin: '24AABCS0123N1Z4',
    email: 'chemical@suratchem.in',
    phone: '+91 261 234 5678',
    category: 'Chemical & Industrial Supplies',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-GJ-24-567890',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-040',
      accountNumber: '040123456789',
      accountName: 'Surat Chemical Industries LLP',
      ifscCode: 'HDFC0040123',
      bankName: 'HDFC Bank',
      branchName: 'Udhna',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-08-05'
    }],
    addresses: [{
      id: 'ADDR-040',
      type: 'Billing',
      addressLine1: 'Plot 123, Pandesara GIDC',
      city: 'Surat',
      state: 'Gujarat',
      stateCode: 'GJ',
      pincode: '394221',
      country: 'India',
      gstin: '24AABCS0123N1Z4',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-08-01',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-08-03',
    entityId: 'ENT-PROCINIX-IN'
  },

  // ========================================
  // VENDORS 41-50: FINAL MIX - COMPLETE COVERAGE
  // ========================================
  {
    id: 'VEN-DEMO-041',
    code: 'VEN-2041',
    name: 'Mumbai Waste Management',
    legalName: 'Mumbai Waste Management Services Pvt Ltd',
    pan: 'AABCM1234O',
    gstin: '27AABCM1234O1Z5',
    email: 'waste@mumbaiwaste.in',
    phone: '+91 22 2901 2345',
    category: 'Waste Management Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [{
      id: 'BA-041',
      accountNumber: '041234567890',
      accountName: 'Mumbai Waste Management Services Pvt Ltd',
      ifscCode: 'ICIC0041234',
      bankName: 'ICICI Bank',
      branchName: 'Goregaon',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-08-10'
    }],
    addresses: [{
      id: 'ADDR-041',
      type: 'Billing',
      addressLine1: 'Facility Complex, Link Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400063',
      country: 'India',
      gstin: '27AABCM1234O1Z5',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-08-05',
    approvedBy: 'Operations Head',
    approvedDate: '2024-08-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-042',
    code: 'VEN-2042',
    name: 'Pune Solar Energy',
    legalName: 'Pune Solar Energy Solutions LLP',
    pan: 'AABCP2345P',
    gstin: '', // UNREGISTERED
    email: 'solar@punesolar.in',
    phone: '+91 20 2723 4567',
    category: 'Renewable Energy Services',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-901234',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-042',
      accountNumber: '042345678901',
      accountName: 'Pune Solar Energy Solutions LLP',
      ifscCode: 'SBIN0042345',
      bankName: 'State Bank of India',
      branchName: 'Aundh',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-08-15'
    }],
    addresses: [{
      id: 'ADDR-042',
      type: 'Billing',
      addressLine1: 'Lane 12, Aundh',
      city: 'Pune',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '411007',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-08-10',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-08-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-043',
    code: 'VEN-2043',
    name: 'Nashik Wine Distributors',
    legalName: 'Nashik Wine Distributors India Pvt Ltd',
    pan: 'AABCN3456Q',
    gstin: '27AABCN3456Q1Z6',
    email: 'wine@nashikwine.in',
    phone: '+91 253 234 5678',
    category: 'Beverage Distribution',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-043',
      accountNumber: '043456789012',
      accountName: 'Nashik Wine Distributors India Pvt Ltd',
      ifscCode: 'HDFC0043456',
      bankName: 'HDFC Bank',
      branchName: 'Nashik City',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-08-20'
    }],
    addresses: [{
      id: 'ADDR-043',
      type: 'Billing',
      addressLine1: 'Vineyard Road, Sula',
      city: 'Nashik',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '422009',
      country: 'India',
      gstin: '27AABCN3456Q1Z6',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-08-15',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-08-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-044',
    code: 'VEN-2044',
    name: 'Bangalore Cybersecurity Experts',
    legalName: 'Bangalore Cybersecurity Experts Pvt Ltd',
    pan: 'AABCB4567R',
    gstin: '29AABCB4567R1Z7',
    email: 'security@bangalorecyber.in',
    phone: '+91 80 2834 5678',
    category: 'Cybersecurity Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    bankAccounts: [{
      id: 'BA-044',
      accountNumber: '044567890123',
      accountName: 'Bangalore Cybersecurity Experts Pvt Ltd',
      ifscCode: 'ICIC0044567',
      bankName: 'ICICI Bank',
      branchName: 'Electronic City',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-08-25'
    }],
    addresses: [{
      id: 'ADDR-044',
      type: 'Billing',
      addressLine1: 'Tower 6, Electronic City Phase 1',
      city: 'Bangalore',
      state: 'Karnataka',
      stateCode: 'KA',
      pincode: '560100',
      country: 'India',
      gstin: '29AABCB4567R1Z7',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-08-20',
    approvedBy: 'IT Head',
    approvedDate: '2024-08-22',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-045',
    code: 'VEN-2045',
    name: 'Thane Textile Printers',
    legalName: 'Thane Textile Printers LLP',
    pan: 'AABCT5678S',
    gstin: '', // UNREGISTERED
    email: 'textiles@thanetextile.in',
    phone: '+91 22 2945 6789',
    category: 'Textile Printing',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-012345',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-045',
      accountNumber: '045678901234',
      accountName: 'Thane Textile Printers LLP',
      ifscCode: 'SBIN0045678',
      bankName: 'State Bank of India',
      branchName: 'Mumbra',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-09-01'
    }],
    addresses: [{
      id: 'ADDR-045',
      type: 'Billing',
      addressLine1: 'Industrial Estate, Mumbra',
      city: 'Thane',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400612',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-08-25',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-08-28',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-046',
    code: 'VEN-2046',
    name: 'Chennai Mobile App Developers',
    legalName: 'Chennai Mobile App Developers Pvt Ltd',
    pan: 'AABCC6789T',
    gstin: '33AABCC6789T1Z8',
    email: 'apps@chennaiapps.in',
    phone: '+91 44 3056 7890',
    category: 'Mobile App Development',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    bankAccounts: [{
      id: 'BA-046',
      accountNumber: '046789012345',
      accountName: 'Chennai Mobile App Developers Pvt Ltd',
      ifscCode: 'HDFC0046789',
      bankName: 'HDFC Bank',
      branchName: 'Velachery',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-09-05'
    }],
    addresses: [{
      id: 'ADDR-046',
      type: 'Billing',
      addressLine1: 'IT Park, OMR Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      stateCode: 'TN',
      pincode: '600042',
      country: 'India',
      gstin: '33AABCC6789T1Z8',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-09-01',
    approvedBy: 'IT Head',
    approvedDate: '2024-09-03',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-047',
    code: 'VEN-2047',
    name: 'Nagpur Steel Traders',
    legalName: 'Nagpur Steel Traders India LLP',
    pan: 'AABCN7890U',
    gstin: '27AABCN7890U1Z9',
    email: 'steel@nagpursteel.in',
    phone: '+91 712 234 5678',
    category: 'Steel & Metal Supplies',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-27-123456',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 15 Days',
    creditDays: 15,
    tdsApplicable: false,
    bankAccounts: [{
      id: 'BA-047',
      accountNumber: '047890123456',
      accountName: 'Nagpur Steel Traders India LLP',
      ifscCode: 'ICIC0047890',
      bankName: 'ICICI Bank',
      branchName: 'Kalamna',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-09-10'
    }],
    addresses: [{
      id: 'ADDR-047',
      type: 'Billing',
      addressLine1: 'Plot 345, Hingna MIDC',
      city: 'Nagpur',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '440016',
      country: 'India',
      gstin: '27AABCN7890U1Z9',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-09-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-09-08',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-048',
    code: 'VEN-2048',
    name: 'Delhi Audit & Compliance',
    legalName: 'Delhi Audit & Compliance Services Pvt Ltd',
    pan: 'AABCD8901V',
    gstin: '', // UNREGISTERED
    email: 'audit@delhiaudit.in',
    phone: '+91 11 3167 8901',
    category: 'Audit & Compliance Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    bankAccounts: [{
      id: 'BA-048',
      accountNumber: '048901234567',
      accountName: 'Delhi Audit & Compliance Services Pvt Ltd',
      ifscCode: 'SBIN0048901',
      bankName: 'State Bank of India',
      branchName: 'Karol Bagh',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-09-15'
    }],
    addresses: [{
      id: 'ADDR-048',
      type: 'Billing',
      addressLine1: 'Office 23, Karol Bagh',
      city: 'New Delhi',
      state: 'Delhi',
      stateCode: 'DL',
      pincode: '110005',
      country: 'India',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-09-10',
    approvedBy: 'Finance Head',
    approvedDate: '2024-09-12',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-049',
    code: 'VEN-2049',
    name: 'Mumbai Fire Safety Systems',
    legalName: 'Mumbai Fire Safety Systems Pvt Ltd',
    pan: 'AABCM9012W',
    gstin: '27AABCM9012W1Z0',
    email: 'fire@mumbaifire.in',
    phone: '+91 22 3278 9012',
    category: 'Fire Safety & Security',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [{
      id: 'BA-049',
      accountNumber: '049012345678',
      accountName: 'Mumbai Fire Safety Systems Pvt Ltd',
      ifscCode: 'HDFC0049012',
      bankName: 'HDFC Bank',
      branchName: 'Malad',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-09-20'
    }],
    addresses: [{
      id: 'ADDR-049',
      type: 'Billing',
      addressLine1: 'Building 78, Link Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '400064',
      country: 'India',
      gstin: '27AABCM9012W1Z0',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-09-15',
    approvedBy: 'Operations Head',
    approvedDate: '2024-09-18',
    entityId: 'ENT-PROCINIX-IN'
  },
  {
    id: 'VEN-DEMO-050',
    code: 'VEN-2050',
    name: 'Pune Analytics & BI Solutions',
    legalName: 'Pune Analytics & BI Solutions Pvt Ltd',
    pan: 'AABCP0123X',
    gstin: '27AABCP0123X1Z1',
    email: 'analytics@puneanalytics.in',
    phone: '+91 20 3389 0123',
    category: 'Analytics & Business Intelligence',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30 Days',
    creditDays: 30,
    tdsApplicable: true,
    tdsSection: '194J',
    bankAccounts: [{
      id: 'BA-050',
      accountNumber: '050123456789',
      accountName: 'Pune Analytics & BI Solutions Pvt Ltd',
      ifscCode: 'ICIC0050123',
      bankName: 'ICICI Bank',
      branchName: 'Hinjewadi',
      accountType: 'Current',
      isPrimary: true,
      verified: true,
      verifiedDate: '2024-09-25'
    }],
    addresses: [{
      id: 'ADDR-050',
      type: 'Billing',
      addressLine1: 'IT Park Phase 2, Hinjewadi',
      city: 'Pune',
      state: 'Maharashtra',
      stateCode: 'MH',
      pincode: '411057',
      country: 'India',
      gstin: '27AABCP0123X1Z1',
      isPrimary: true
    }],
    createdBy: 'System',
    createdDate: '2024-09-20',
    approvedBy: 'IT Head',
    approvedDate: '2024-09-22',
    entityId: 'ENT-PROCINIX-IN'
  }
];
