import { createContext, useContext, useState, ReactNode } from 'react';

export type PermissionKey = string;

export interface UserRole {
  roleId: string;
  roleName: string;
  permissions: PermissionKey[];
}

export interface Company {
  id: string;
  name: string;
  code: string;
  logo?: string;
}

interface FinanceRBACContextType {
  currentRole: UserRole;
  availableRoles: UserRole[];
  currentCompany: Company;
  availableCompanies: Company[];
  switchRole: (roleId: string) => void;
  switchCompany: (companyId: string) => void;
  hasPermission: (permission: PermissionKey) => boolean;
  hasAnyPermission: (permissions: PermissionKey[]) => boolean;
  hasCreatePermission: (resourcePrefix: string) => boolean;
}

const FinanceRBACContext = createContext<FinanceRBACContextType | undefined>(undefined);

// Comprehensive permission definitions
const PERMISSIONS = {
  // AP Automation
  PROCUREMENT: { VIEW: 'PROCUREMENT.VIEW', CREATE: 'PROCUREMENT.CREATE', EDIT: 'PROCUREMENT.EDIT', APPROVE: 'PROCUREMENT.APPROVE' },
  AP_INVOICE: { VIEW: 'AP_INVOICE.VIEW', CREATE: 'AP_INVOICE.CREATE', EDIT: 'AP_INVOICE.EDIT', APPROVE: 'AP_INVOICE.APPROVE', POST: 'AP_INVOICE.POST' },
  PAYMENT: { VIEW: 'PAYMENT.VIEW', CREATE: 'PAYMENT.CREATE', EXECUTE: 'PAYMENT.EXECUTE', APPROVE: 'PAYMENT.APPROVE' },
  ADVANCE: { VIEW: 'ADVANCE.VIEW', CREATE: 'ADVANCE.CREATE', EDIT: 'ADVANCE.EDIT', APPROVE: 'ADVANCE.APPROVE', PROCESS: 'ADVANCE.PROCESS' },
  VENDOR: { VIEW: 'VENDOR.VIEW', CREATE: 'VENDOR.CREATE', EDIT: 'VENDOR.EDIT', APPROVE: 'VENDOR.APPROVE' },
  SOURCING: { VIEW: 'SOURCING.VIEW', CREATE: 'SOURCING.CREATE', MANAGE: 'SOURCING.MANAGE' },
  BUDGET: { VIEW: 'BUDGET.VIEW', CREATE: 'BUDGET.CREATE', EDIT: 'BUDGET.EDIT', APPROVE: 'BUDGET.APPROVE' },
  FIXED_ASSET: { VIEW: 'FIXED_ASSET.VIEW', CREATE: 'FIXED_ASSET.CREATE', EDIT: 'FIXED_ASSET.EDIT', DEPRECIATE: 'FIXED_ASSET.DEPRECIATE' },
  
  // AR Automation
  CUSTOMER: { VIEW: 'CUSTOMER.VIEW', CREATE: 'CUSTOMER.CREATE', EDIT: 'CUSTOMER.EDIT', APPROVE: 'CUSTOMER.APPROVE' },
  AR_INVOICE: { VIEW: 'AR_INVOICE.VIEW', CREATE: 'AR_INVOICE.CREATE', EDIT: 'AR_INVOICE.EDIT', APPROVE: 'AR_INVOICE.APPROVE' },
  COLLECTION: { VIEW: 'COLLECTION.VIEW', CREATE: 'COLLECTION.CREATE', MANAGE: 'COLLECTION.MANAGE', APPROVE: 'COLLECTION.APPROVE' },
  CREDIT_NOTE: { VIEW: 'CREDIT_NOTE.VIEW', CREATE: 'CREDIT_NOTE.CREATE', APPROVE: 'CREDIT_NOTE.APPROVE' },
  REVENUE: { VIEW: 'REVENUE.VIEW', RECOGNIZE: 'REVENUE.RECOGNIZE', DEFER: 'REVENUE.DEFER' },
  
  // R2R Automation
  GENERAL_LEDGER: { VIEW: 'GENERAL_LEDGER.VIEW', POST: 'GENERAL_LEDGER.POST', REVERSE: 'GENERAL_LEDGER.REVERSE' },
  FINANCIAL_CLOSE: { VIEW: 'FINANCIAL_CLOSE.VIEW', EXECUTE: 'FINANCIAL_CLOSE.EXECUTE', APPROVE: 'FINANCIAL_CLOSE.APPROVE' },
  FINANCIAL_STATEMENT: { VIEW: 'FINANCIAL_STATEMENT.VIEW', GENERATE: 'FINANCIAL_STATEMENT.GENERATE', APPROVE: 'FINANCIAL_STATEMENT.APPROVE' },
  CONSOLIDATION: { VIEW: 'CONSOLIDATION.VIEW', EXECUTE: 'CONSOLIDATION.EXECUTE', APPROVE: 'CONSOLIDATION.APPROVE' },
  CASHFLOW: { VIEW: 'CASHFLOW.VIEW', FORECAST: 'CASHFLOW.FORECAST', ANALYZE: 'CASHFLOW.ANALYZE' },
  VARIANCE: { VIEW: 'VARIANCE.VIEW', ANALYZE: 'VARIANCE.ANALYZE', COMMENT: 'VARIANCE.COMMENT' },
  
  // Masters & Reports
  MASTERS: { VIEW: 'MASTERS.VIEW', CREATE: 'MASTERS.CREATE', EDIT: 'MASTERS.EDIT', APPROVE: 'MASTERS.APPROVE' },
  REPORTS: { VIEW: 'REPORTS.VIEW', EXPORT: 'REPORTS.EXPORT', SCHEDULE: 'REPORTS.SCHEDULE' },
  
  // Global
  DASHBOARD: { VIEW: 'DASHBOARD.VIEW', CUSTOMIZE: 'DASHBOARD.CUSTOMIZE' },
  APPROVALS: { VIEW: 'APPROVALS.VIEW', APPROVE: 'APPROVALS.APPROVE', REJECT: 'APPROVALS.REJECT' },
  TASKS: { VIEW: 'TASKS.VIEW', MANAGE: 'TASKS.MANAGE' },
  AUDIT_LOG: { VIEW: 'AUDIT_LOG.VIEW', EXPORT: 'AUDIT_LOG.EXPORT' },
  SETTINGS: { VIEW: 'SETTINGS.VIEW', EDIT: 'SETTINGS.EDIT' },
};

// Predefined roles with specific permissions
const userRolesData: UserRole[] = [
  {
    roleId: 'cfo',
    roleName: 'CFO',
    permissions: [
      // Full view access across all modules
      PERMISSIONS.PROCUREMENT.VIEW,
      PERMISSIONS.AP_INVOICE.VIEW,
      PERMISSIONS.AP_INVOICE.APPROVE,
      PERMISSIONS.PAYMENT.VIEW,
      PERMISSIONS.PAYMENT.APPROVE,
      PERMISSIONS.ADVANCE.VIEW,
      PERMISSIONS.ADVANCE.APPROVE,
      PERMISSIONS.VENDOR.VIEW,
      PERMISSIONS.SOURCING.VIEW,
      PERMISSIONS.BUDGET.VIEW,
      PERMISSIONS.BUDGET.APPROVE,
      PERMISSIONS.FIXED_ASSET.VIEW,
      PERMISSIONS.CUSTOMER.VIEW,
      PERMISSIONS.AR_INVOICE.VIEW,
      PERMISSIONS.AR_INVOICE.APPROVE,
      PERMISSIONS.COLLECTION.VIEW,
      PERMISSIONS.CREDIT_NOTE.VIEW,
      PERMISSIONS.CREDIT_NOTE.APPROVE,
      PERMISSIONS.REVENUE.VIEW,
      PERMISSIONS.GENERAL_LEDGER.VIEW,
      PERMISSIONS.FINANCIAL_CLOSE.VIEW,
      PERMISSIONS.FINANCIAL_CLOSE.APPROVE,
      PERMISSIONS.FINANCIAL_STATEMENT.VIEW,
      PERMISSIONS.FINANCIAL_STATEMENT.APPROVE,
      PERMISSIONS.CONSOLIDATION.VIEW,
      PERMISSIONS.CONSOLIDATION.APPROVE,
      PERMISSIONS.CASHFLOW.VIEW,
      PERMISSIONS.CASHFLOW.FORECAST,
      PERMISSIONS.VARIANCE.VIEW,
      PERMISSIONS.VARIANCE.ANALYZE,
      PERMISSIONS.MASTERS.VIEW,
      PERMISSIONS.REPORTS.VIEW,
      PERMISSIONS.REPORTS.EXPORT,
      PERMISSIONS.DASHBOARD.VIEW,
      PERMISSIONS.DASHBOARD.CUSTOMIZE,
      PERMISSIONS.APPROVALS.VIEW,
      PERMISSIONS.APPROVALS.APPROVE,
      PERMISSIONS.TASKS.VIEW,
      PERMISSIONS.AUDIT_LOG.VIEW,
      PERMISSIONS.AUDIT_LOG.EXPORT,
      PERMISSIONS.SETTINGS.VIEW,
    ]
  },
  {
    roleId: 'ap-manager',
    roleName: 'AP Manager',
    permissions: [
      // Full AP access
      PERMISSIONS.PROCUREMENT.VIEW,
      PERMISSIONS.PROCUREMENT.CREATE,
      PERMISSIONS.PROCUREMENT.EDIT,
      PERMISSIONS.PROCUREMENT.APPROVE,
      PERMISSIONS.AP_INVOICE.VIEW,
      PERMISSIONS.AP_INVOICE.CREATE,
      PERMISSIONS.AP_INVOICE.EDIT,
      PERMISSIONS.AP_INVOICE.APPROVE,
      PERMISSIONS.AP_INVOICE.POST,
      PERMISSIONS.PAYMENT.VIEW,
      PERMISSIONS.PAYMENT.CREATE,
      PERMISSIONS.PAYMENT.APPROVE,
      PERMISSIONS.ADVANCE.VIEW,
      PERMISSIONS.ADVANCE.CREATE,
      PERMISSIONS.ADVANCE.EDIT,
      PERMISSIONS.ADVANCE.APPROVE,
      PERMISSIONS.VENDOR.VIEW,
      PERMISSIONS.VENDOR.CREATE,
      PERMISSIONS.VENDOR.EDIT,
      PERMISSIONS.VENDOR.APPROVE,
      PERMISSIONS.SOURCING.VIEW,
      PERMISSIONS.SOURCING.CREATE,
      PERMISSIONS.SOURCING.MANAGE,
      PERMISSIONS.BUDGET.VIEW,
      PERMISSIONS.BUDGET.EDIT,
      PERMISSIONS.FIXED_ASSET.VIEW,
      PERMISSIONS.FIXED_ASSET.CREATE,
      PERMISSIONS.FIXED_ASSET.EDIT,
      PERMISSIONS.MASTERS.VIEW,
      PERMISSIONS.MASTERS.CREATE,
      PERMISSIONS.MASTERS.EDIT,
      PERMISSIONS.REPORTS.VIEW,
      PERMISSIONS.REPORTS.EXPORT,
      PERMISSIONS.DASHBOARD.VIEW,
      PERMISSIONS.APPROVALS.VIEW,
      PERMISSIONS.APPROVALS.APPROVE,
      PERMISSIONS.TASKS.VIEW,
      PERMISSIONS.TASKS.MANAGE,
      PERMISSIONS.AUDIT_LOG.VIEW,
      PERMISSIONS.SETTINGS.VIEW,
    ]
  },
  {
    roleId: 'ap-clerk',
    roleName: 'AP Clerk',
    permissions: [
      // Limited AP access - data entry only
      PERMISSIONS.PROCUREMENT.VIEW,
      PERMISSIONS.AP_INVOICE.VIEW,
      PERMISSIONS.AP_INVOICE.CREATE,
      PERMISSIONS.PAYMENT.VIEW,
      PERMISSIONS.VENDOR.VIEW,
      PERMISSIONS.MASTERS.VIEW,
      PERMISSIONS.REPORTS.VIEW,
      PERMISSIONS.DASHBOARD.VIEW,
      PERMISSIONS.TASKS.VIEW,
    ]
  },
  {
    roleId: 'ar-manager',
    roleName: 'AR Manager',
    permissions: [
      // Full AR access
      PERMISSIONS.CUSTOMER.VIEW,
      PERMISSIONS.CUSTOMER.CREATE,
      PERMISSIONS.CUSTOMER.EDIT,
      PERMISSIONS.CUSTOMER.APPROVE,
      PERMISSIONS.AR_INVOICE.VIEW,
      PERMISSIONS.AR_INVOICE.CREATE,
      PERMISSIONS.AR_INVOICE.EDIT,
      PERMISSIONS.AR_INVOICE.APPROVE,
      PERMISSIONS.COLLECTION.VIEW,
      PERMISSIONS.COLLECTION.CREATE,
      PERMISSIONS.COLLECTION.MANAGE,
      PERMISSIONS.COLLECTION.APPROVE,
      PERMISSIONS.CREDIT_NOTE.VIEW,
      PERMISSIONS.CREDIT_NOTE.CREATE,
      PERMISSIONS.CREDIT_NOTE.APPROVE,
      PERMISSIONS.REVENUE.VIEW,
      PERMISSIONS.REVENUE.RECOGNIZE,
      PERMISSIONS.REVENUE.DEFER,
      PERMISSIONS.MASTERS.VIEW,
      PERMISSIONS.MASTERS.CREATE,
      PERMISSIONS.MASTERS.EDIT,
      PERMISSIONS.REPORTS.VIEW,
      PERMISSIONS.REPORTS.EXPORT,
      PERMISSIONS.DASHBOARD.VIEW,
      PERMISSIONS.APPROVALS.VIEW,
      PERMISSIONS.APPROVALS.APPROVE,
      PERMISSIONS.TASKS.VIEW,
      PERMISSIONS.TASKS.MANAGE,
      PERMISSIONS.AUDIT_LOG.VIEW,
      PERMISSIONS.SETTINGS.VIEW,
    ]
  },
  {
    roleId: 'finance-controller',
    roleName: 'Finance Controller',
    permissions: [
      // View AP & AR, Full R2R access
      PERMISSIONS.PROCUREMENT.VIEW,
      PERMISSIONS.AP_INVOICE.VIEW,
      PERMISSIONS.PAYMENT.VIEW,
      PERMISSIONS.ADVANCE.VIEW,
      PERMISSIONS.VENDOR.VIEW,
      PERMISSIONS.CUSTOMER.VIEW,
      PERMISSIONS.AR_INVOICE.VIEW,
      PERMISSIONS.COLLECTION.VIEW,
      PERMISSIONS.REVENUE.VIEW,
      PERMISSIONS.GENERAL_LEDGER.VIEW,
      PERMISSIONS.GENERAL_LEDGER.POST,
      PERMISSIONS.GENERAL_LEDGER.REVERSE,
      PERMISSIONS.FINANCIAL_CLOSE.VIEW,
      PERMISSIONS.FINANCIAL_CLOSE.EXECUTE,
      PERMISSIONS.FINANCIAL_STATEMENT.VIEW,
      PERMISSIONS.FINANCIAL_STATEMENT.GENERATE,
      PERMISSIONS.CONSOLIDATION.VIEW,
      PERMISSIONS.CONSOLIDATION.EXECUTE,
      PERMISSIONS.CASHFLOW.VIEW,
      PERMISSIONS.CASHFLOW.FORECAST,
      PERMISSIONS.CASHFLOW.ANALYZE,
      PERMISSIONS.VARIANCE.VIEW,
      PERMISSIONS.VARIANCE.ANALYZE,
      PERMISSIONS.VARIANCE.COMMENT,
      PERMISSIONS.MASTERS.VIEW,
      PERMISSIONS.MASTERS.EDIT,
      PERMISSIONS.REPORTS.VIEW,
      PERMISSIONS.REPORTS.EXPORT,
      PERMISSIONS.DASHBOARD.VIEW,
      PERMISSIONS.APPROVALS.VIEW,
      PERMISSIONS.APPROVALS.APPROVE,
      PERMISSIONS.TASKS.VIEW,
      PERMISSIONS.TASKS.MANAGE,
      PERMISSIONS.AUDIT_LOG.VIEW,
      PERMISSIONS.SETTINGS.VIEW,
    ]
  },
  {
    roleId: 'accountant',
    roleName: 'Accountant',
    permissions: [
      // AP & AR data entry, R2R view
      PERMISSIONS.AP_INVOICE.VIEW,
      PERMISSIONS.AP_INVOICE.CREATE,
      PERMISSIONS.PAYMENT.VIEW,
      PERMISSIONS.ADVANCE.VIEW,
      PERMISSIONS.VENDOR.VIEW,
      PERMISSIONS.AR_INVOICE.VIEW,
      PERMISSIONS.AR_INVOICE.CREATE,
      PERMISSIONS.CUSTOMER.VIEW,
      PERMISSIONS.GENERAL_LEDGER.VIEW,
      PERMISSIONS.GENERAL_LEDGER.POST,
      PERMISSIONS.FINANCIAL_CLOSE.VIEW,
      PERMISSIONS.CASHFLOW.VIEW,
      PERMISSIONS.MASTERS.VIEW,
      PERMISSIONS.REPORTS.VIEW,
      PERMISSIONS.DASHBOARD.VIEW,
      PERMISSIONS.TASKS.VIEW,
    ]
  },
  {
    roleId: 'auditor',
    roleName: 'Auditor',
    permissions: [
      // View-only access to everything
      PERMISSIONS.PROCUREMENT.VIEW,
      PERMISSIONS.AP_INVOICE.VIEW,
      PERMISSIONS.PAYMENT.VIEW,
      PERMISSIONS.ADVANCE.VIEW,
      PERMISSIONS.VENDOR.VIEW,
      PERMISSIONS.SOURCING.VIEW,
      PERMISSIONS.BUDGET.VIEW,
      PERMISSIONS.FIXED_ASSET.VIEW,
      PERMISSIONS.CUSTOMER.VIEW,
      PERMISSIONS.AR_INVOICE.VIEW,
      PERMISSIONS.COLLECTION.VIEW,
      PERMISSIONS.CREDIT_NOTE.VIEW,
      PERMISSIONS.REVENUE.VIEW,
      PERMISSIONS.GENERAL_LEDGER.VIEW,
      PERMISSIONS.FINANCIAL_CLOSE.VIEW,
      PERMISSIONS.FINANCIAL_STATEMENT.VIEW,
      PERMISSIONS.CONSOLIDATION.VIEW,
      PERMISSIONS.CASHFLOW.VIEW,
      PERMISSIONS.VARIANCE.VIEW,
      PERMISSIONS.MASTERS.VIEW,
      PERMISSIONS.REPORTS.VIEW,
      PERMISSIONS.REPORTS.EXPORT,
      PERMISSIONS.DASHBOARD.VIEW,
      PERMISSIONS.AUDIT_LOG.VIEW,
      PERMISSIONS.AUDIT_LOG.EXPORT,
    ]
  }
];

const companiesData: Company[] = [
  { id: 'comp-1', name: 'Acme Corporation', code: 'ACME' },
  { id: 'comp-2', name: 'Global Industries Ltd', code: 'GLBL' },
  { id: 'comp-3', name: 'TechVentures Inc', code: 'TECH' },
  { id: 'comp-4', name: 'Premier Manufacturing', code: 'PREM' },
];

export function FinanceRBACProvider({ children }: { children: ReactNode }) {
  const [currentRole, setCurrentRole] = useState<UserRole>(userRolesData[0]);
  const [currentCompany, setCurrentCompany] = useState<Company>(companiesData[0]);

  const switchRole = (roleId: string) => {
    const role = userRolesData.find(r => r.roleId === roleId);
    if (role) {
      setCurrentRole(role);
    }
  };

  const switchCompany = (companyId: string) => {
    const company = companiesData.find(c => c.id === companyId);
    if (company) {
      setCurrentCompany(company);
    }
  };

  const hasPermission = (permission: PermissionKey): boolean => {
    return currentRole.permissions.includes(permission);
  };

  const hasAnyPermission = (permissions: PermissionKey[]): boolean => {
    return permissions.some(perm => currentRole.permissions.includes(perm));
  };

  const hasCreatePermission = (resourcePrefix: string): boolean => {
    // Check if user has any CREATE permission for the resource
    return currentRole.permissions.some(perm => 
      perm.startsWith(resourcePrefix) && perm.includes('.CREATE')
    );
  };

  return (
    <FinanceRBACContext.Provider
      value={{
        currentRole,
        availableRoles: userRolesData,
        currentCompany,
        availableCompanies: companiesData,
        switchRole,
        switchCompany,
        hasPermission,
        hasAnyPermission,
        hasCreatePermission,
      }}
    >
      {children}
    </FinanceRBACContext.Provider>
  );
}

export function useFinanceRBAC() {
  const context = useContext(FinanceRBACContext);
  if (context === undefined) {
    throw new Error('useFinanceRBAC must be used within a FinanceRBACProvider');
  }
  return context;
}

export { PERMISSIONS };