/**
 * MULTI-ENTITY & MULTI-COUNTRY MASTER DATA
 *
 * Comprehensive master data for:
 * - Subko Coffee Pvt Ltd – India (INR, GST)
 * - Subko Coffee – Dubai (AED, VAT)
 * - Procinix Ltd – India (INR, GST)
 *
 * SAFETY: All data is ADDITIVE. Existing masters remain unchanged.
 */

import type {
  VendorMaster,
  BankMaster,
  CostCentreMaster,
  TaxCodeMaster,
  DepartmentMaster,
} from './MasterDataContext';

// ============================================================================
// MULTI-ENTITY VENDORS
// ============================================================================

export const MULTI_ENTITY_VENDORS: VendorMaster[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // SUBKO COFFEE INDIA VENDORS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'VEN-SUBKO-IN-001',
    code: 'SUBKO-IN-V001',
    name: 'Coorg Coffee Estates',
    legalName: 'Coorg Coffee Estates Private Limited',
    pan: 'AABCC1234D',
    gstin: '29AABCC1234D1Z1',
    email: 'sales@coorgcoffee.in',
    phone: '+91 9845123456',
    category: 'Coffee Beans Supplier',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-KA-001234',
    msmeCategory: 'Small',
    status: 'Active',
    approvalStatus: 'Approved',
    paymentTerms: 'Net 30',
    creditDays: 30,
    entityId: 'ENT-SUBKO-IN',
    entityName: 'Subko Coffee Pvt Ltd – India',
    country: 'India',
    currency: 'INR',
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [
      {
        id: 'BA-SUBKO-IN-001',
        accountNumber: '123456789012',
        accountName: 'Coorg Coffee Estates Pvt Ltd',
        ifscCode: 'HDFC0001234',
        bankName: 'HDFC Bank',
        branchName: 'Coorg Branch',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-01-15',
      },
    ],
    addresses: [
      {
        id: 'ADDR-SUBKO-IN-001',
        type: 'Registered',
        addressLine1: 'Estate Road, Madikeri',
        city: 'Coorg',
        state: 'Karnataka',
        stateCode: 'KA',
        pincode: '571201',
        country: 'India',
        gstin: '29AABCC1234D1Z1',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-01-10',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-01-12',
  },
  {
    id: 'VEN-SUBKO-IN-002',
    code: 'SUBKO-IN-V002',
    name: 'Premium Packaging Solutions',
    legalName: 'Premium Packaging Solutions India Pvt Ltd',
    pan: 'AABPP5678E',
    gstin: '29AABPP5678E1Z2',
    email: 'orders@premiumpkg.in',
    phone: '+91 9876543210',
    category: 'Packaging Materials',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    approvalStatus: 'Changes Requested',
    paymentTerms: 'Net 45',
    creditDays: 45,
    entityId: 'ENT-SUBKO-IN',
    entityName: 'Subko Coffee Pvt Ltd – India',
    country: 'India',
    currency: 'INR',
    tdsApplicable: false,
    bankAccounts: [
      {
        id: 'BA-SUBKO-IN-002',
        accountNumber: '234567890123',
        accountName: 'Premium Packaging Solutions India Pvt Ltd',
        ifscCode: 'ICIC0005678',
        bankName: 'ICICI Bank',
        branchName: 'Bangalore',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-02-01',
      },
    ],
    addresses: [
      {
        id: 'ADDR-SUBKO-IN-002',
        type: 'Registered',
        addressLine1: 'Peenya Industrial Area, Phase 2',
        city: 'Bangalore',
        state: 'Karnataka',
        stateCode: 'KA',
        pincode: '560058',
        country: 'India',
        gstin: '29AABPP5678E1Z2',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-02-01',
  },
  {
    id: 'VEN-SUBKO-IN-003',
    code: 'SUBKO-IN-V003',
    name: 'Urban Logistics Pvt Ltd',
    legalName: 'Urban Logistics Private Limited',
    pan: 'AABUL9012F',
    gstin: '29AABUL9012F1Z3',
    email: 'support@urbanlogistics.in',
    phone: '+91 9123456789',
    category: 'Transportation',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-KA-005678',
    msmeCategory: 'Micro',
    status: 'Active',
    paymentTerms: 'Net 15',
    creditDays: 15,
    entityId: 'ENT-SUBKO-IN',
    entityName: 'Subko Coffee Pvt Ltd – India',
    country: 'India',
    currency: 'INR',
    tdsApplicable: true,
    tdsSection: '194C',
    bankAccounts: [
      {
        id: 'BA-SUBKO-IN-003',
        accountNumber: '345678901234',
        accountName: 'Urban Logistics Pvt Ltd',
        ifscCode: 'SBIN0012345',
        bankName: 'State Bank of India',
        branchName: 'Indiranagar',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-03-10',
      },
    ],
    addresses: [
      {
        id: 'ADDR-SUBKO-IN-003',
        type: 'Registered',
        addressLine1: 'Transport Nagar, Whitefield',
        city: 'Bangalore',
        state: 'Karnataka',
        stateCode: 'KA',
        pincode: '560066',
        country: 'India',
        gstin: '29AABUL9012F1Z3',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-03-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-03-08',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SUBKO COFFEE DUBAI (UAE) VENDORS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'VEN-SUBKO-UAE-001',
    code: 'SUBKO-UAE-V001',
    name: 'Arabian Coffee Trading LLC',
    legalName: 'Arabian Coffee Trading LLC',
    pan: '',
    gstin: '',
    email: 'sales@arabiancoffee.ae',
    phone: '+971 50 123 4567',
    category: 'Coffee Beans Supplier',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30',
    creditDays: 30,
    entityId: 'ENT-SUBKO-UAE',
    entityName: 'Subko Coffee – Dubai',
    country: 'UAE',
    currency: 'AED',
    vatRegistrationNumber: '100234567800001',
    emiratesId: 'AE-DXB-12345',
    bankAccounts: [
      {
        id: 'BA-SUBKO-UAE-001',
        accountNumber: 'AE070331234567890123456',
        accountName: 'Arabian Coffee Trading LLC',
        ifscCode: '', // Not applicable for UAE
        bankName: 'Emirates NBD',
        branchName: 'Dubai Investment Park',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-01-20',
      },
    ],
    addresses: [
      {
        id: 'ADDR-SUBKO-UAE-001',
        type: 'Registered',
        addressLine1: 'Dubai Investment Park 1, Building 12',
        city: 'Dubai',
        state: 'Dubai',
        stateCode: 'DXB',
        pincode: '00000',
        country: 'UAE',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-01-15',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-01-18',
  },
  {
    id: 'VEN-SUBKO-UAE-002',
    code: 'SUBKO-UAE-V002',
    name: 'Gulf Packaging Industries',
    legalName: 'Gulf Packaging Industries LLC',
    pan: '',
    gstin: '',
    email: 'info@gulfpackaging.ae',
    phone: '+971 50 234 5678',
    category: 'Packaging Materials',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 45',
    creditDays: 45,
    entityId: 'ENT-SUBKO-UAE',
    entityName: 'Subko Coffee – Dubai',
    country: 'UAE',
    currency: 'AED',
    vatRegistrationNumber: '100345678900002',
    emiratesId: 'AE-DXB-23456',
    bankAccounts: [
      {
        id: 'BA-SUBKO-UAE-002',
        accountNumber: 'AE080331234567890234567',
        accountName: 'Gulf Packaging Industries LLC',
        ifscCode: '',
        bankName: 'Mashreq Bank',
        branchName: 'Jebel Ali',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-02-10',
      },
    ],
    addresses: [
      {
        id: 'ADDR-SUBKO-UAE-002',
        type: 'Registered',
        addressLine1: 'Jebel Ali Free Zone, Unit 45',
        city: 'Dubai',
        state: 'Dubai',
        stateCode: 'DXB',
        pincode: '00000',
        country: 'UAE',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-02-05',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-02-08',
  },
  {
    id: 'VEN-SUBKO-UAE-003',
    code: 'SUBKO-UAE-V003',
    name: 'Emirates Logistics Services',
    legalName: 'Emirates Logistics Services LLC',
    pan: '',
    gstin: '',
    email: 'ops@emirateslogistics.ae',
    phone: '+971 50 345 6789',
    category: 'Transportation',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 15',
    creditDays: 15,
    entityId: 'ENT-SUBKO-UAE',
    entityName: 'Subko Coffee – Dubai',
    country: 'UAE',
    currency: 'AED',
    vatRegistrationNumber: '100456789000003',
    emiratesId: 'AE-DXB-34567',
    bankAccounts: [
      {
        id: 'BA-SUBKO-UAE-003',
        accountNumber: 'AE090331234567890345678',
        accountName: 'Emirates Logistics Services LLC',
        ifscCode: '',
        bankName: 'Abu Dhabi Commercial Bank',
        branchName: 'Dubai Main',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-03-01',
      },
    ],
    addresses: [
      {
        id: 'ADDR-SUBKO-UAE-003',
        type: 'Registered',
        addressLine1: 'Al Quoz Industrial Area 3',
        city: 'Dubai',
        state: 'Dubai',
        stateCode: 'DXB',
        pincode: '00000',
        country: 'UAE',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-02-25',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-02-28',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PROCINIX INDIA VENDORS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'VEN-PROC-IN-001',
    code: 'PROC-IN-V001',
    name: 'Tech Solutions India Pvt Ltd',
    legalName: 'Tech Solutions India Private Limited',
    pan: 'AABTS1234G',
    gstin: '27AABTS1234G1Z1',
    email: 'sales@techsolutions.in',
    phone: '+91 22 12345678',
    category: 'IT Services',
    vendorType: 'Domestic',
    msmeRegistered: false,
    status: 'Active',
    paymentTerms: 'Net 30',
    creditDays: 30,
    entityId: 'ENT-PROCINIX-IN',
    entityName: 'Procinix Ltd – India',
    country: 'India',
    currency: 'INR',
    tdsApplicable: true,
    tdsSection: '194J',
    bankAccounts: [
      {
        id: 'BA-PROC-IN-001',
        accountNumber: '456789012345',
        accountName: 'Tech Solutions India Pvt Ltd',
        ifscCode: 'HDFC0002468',
        bankName: 'HDFC Bank',
        branchName: 'Andheri',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-01-25',
      },
    ],
    addresses: [
      {
        id: 'ADDR-PROC-IN-001',
        type: 'Registered',
        addressLine1: 'Andheri East, IT Park, Building A',
        city: 'Mumbai',
        state: 'Maharashtra',
        stateCode: 'MH',
        pincode: '400093',
        country: 'India',
        gstin: '27AABTS1234G1Z1',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-01-20',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-01-23',
  },
  {
    id: 'VEN-PROC-IN-002',
    code: 'PROC-IN-V002',
    name: 'Office Mart Supplies',
    legalName: 'Office Mart Supplies Private Limited',
    pan: 'AABOM5678H',
    gstin: '27AABOM5678H1Z2',
    email: 'orders@officemart.in',
    phone: '+91 22 23456789',
    category: 'Office Supplies',
    vendorType: 'Domestic',
    msmeRegistered: true,
    msmeNumber: 'MSME-MH-007890',
    msmeCategory: 'Small',
    status: 'Active',
    paymentTerms: 'Net 45',
    creditDays: 45,
    entityId: 'ENT-PROCINIX-IN',
    entityName: 'Procinix Ltd – India',
    country: 'India',
    currency: 'INR',
    tdsApplicable: false,
    bankAccounts: [
      {
        id: 'BA-PROC-IN-002',
        accountNumber: '567890123456',
        accountName: 'Office Mart Supplies Pvt Ltd',
        ifscCode: 'ICIC0001357',
        bankName: 'ICICI Bank',
        branchName: 'Bandra',
        accountType: 'Current',
        isPrimary: true,
        verified: true,
        verifiedDate: '2024-02-15',
      },
    ],
    addresses: [
      {
        id: 'ADDR-PROC-IN-002',
        type: 'Registered',
        addressLine1: 'Bandra Kurla Complex, Unit 23',
        city: 'Mumbai',
        state: 'Maharashtra',
        stateCode: 'MH',
        pincode: '400051',
        country: 'India',
        gstin: '27AABOM5678H1Z2',
        isPrimary: true,
      },
    ],
    createdBy: 'Admin',
    createdDate: '2024-02-10',
    approvedBy: 'Procurement Head',
    approvedDate: '2024-02-13',
  },
];

// ============================================================================
// MULTI-ENTITY BANK ACCOUNTS
// ============================================================================

export const MULTI_ENTITY_BANKS: BankMaster[] = [
  // Subko Coffee India Banks
  {
    id: 'BANK-SUBKO-IN-001',
    bankName: 'HDFC Bank',
    branchName: 'Lavelle Road Branch',
    ifscCode: 'HDFC0001122',
    accountNumber: '50100123456789',
    accountName: 'Subko Coffee Private Limited',
    accountType: 'Current',
    entityId: 'ENT-SUBKO-IN',
    entityName: 'Subko Coffee Pvt Ltd – India',
    currency: 'INR',
    isActive: true,
    isPrimary: true,
  },
  {
    id: 'BANK-SUBKO-IN-002',
    bankName: 'ICICI Bank',
    branchName: 'MG Road Branch',
    ifscCode: 'ICIC0002233',
    accountNumber: '60200234567890',
    accountName: 'Subko Coffee Private Limited',
    accountType: 'Current',
    entityId: 'ENT-SUBKO-IN',
    entityName: 'Subko Coffee Pvt Ltd – India',
    currency: 'INR',
    isActive: true,
    isPrimary: false,
  },
  // Subko Coffee UAE Banks
  {
    id: 'BANK-SUBKO-UAE-001',
    bankName: 'Emirates NBD',
    branchName: 'Dubai Investment Park',
    ifscCode: '', // Not applicable
    accountNumber: 'AE070331000567890123456',
    accountName: 'Subko Coffee LLC',
    accountType: 'Current',
    entityId: 'ENT-SUBKO-UAE',
    entityName: 'Subko Coffee – Dubai',
    currency: 'AED',
    isActive: true,
    isPrimary: true,
  },
  {
    id: 'BANK-SUBKO-UAE-002',
    bankName: 'Mashreq Bank',
    branchName: 'DIFC Branch',
    ifscCode: '',
    accountNumber: 'AE080331000678901234567',
    accountName: 'Subko Coffee LLC',
    accountType: 'Current',
    entityId: 'ENT-SUBKO-UAE',
    entityName: 'Subko Coffee – Dubai',
    currency: 'AED',
    isActive: true,
    isPrimary: false,
  },
  // Procinix India Banks
  {
    id: 'BANK-PROC-IN-001',
    bankName: 'HDFC Bank',
    branchName: 'Nariman Point Branch',
    ifscCode: 'HDFC0003344',
    accountNumber: '50100345678901',
    accountName: 'Procinix Limited',
    accountType: 'Current',
    entityId: 'ENT-PROCINIX-IN',
    entityName: 'Procinix Ltd – India',
    currency: 'INR',
    isActive: true,
    isPrimary: true,
  },
  {
    id: 'BANK-PROC-IN-002',
    bankName: 'State Bank of India',
    branchName: 'BKC Branch',
    ifscCode: 'SBIN0004455',
    accountNumber: '40300456789012',
    accountName: 'Procinix Limited',
    accountType: 'Current',
    entityId: 'ENT-PROCINIX-IN',
    entityName: 'Procinix Ltd – India',
    currency: 'INR',
    isActive: true,
    isPrimary: false,
  },
];

// ============================================================================
// MULTI-ENTITY COST CENTRES
// ============================================================================

export const MULTI_ENTITY_COST_CENTRES: CostCentreMaster[] = [
  // Subko Coffee India Cost Centres
  {
    id: 'CC-SUBKO-IN-001',
    code: 'SUBKO-IN-PROD',
    name: 'Production - Bangalore',
    description: 'Coffee roasting and packaging operations',
    departmentId: 'DEPT-001',
    departmentName: 'Production',
    headOfCentre: 'Rajesh Kumar',
    isActive: true,
    budgetAllocated: 5000000,
  },
  {
    id: 'CC-SUBKO-IN-002',
    code: 'SUBKO-IN-SALES',
    name: 'Sales & Marketing - India',
    description: 'Sales and marketing activities for Indian market',
    departmentId: 'DEPT-002',
    departmentName: 'Sales',
    headOfCentre: 'Priya Sharma',
    isActive: true,
    budgetAllocated: 3000000,
  },
  {
    id: 'CC-SUBKO-IN-003',
    code: 'SUBKO-IN-ADMIN',
    name: 'Administration - Bangalore',
    description: 'General administration and support',
    departmentId: 'DEPT-003',
    departmentName: 'Administration',
    headOfCentre: 'Amit Patel',
    isActive: true,
    budgetAllocated: 2000000,
  },
  // Subko Coffee UAE Cost Centres
  {
    id: 'CC-SUBKO-UAE-001',
    code: 'SUBKO-UAE-RETAIL',
    name: 'Retail Operations - Dubai',
    description: 'Café and retail store operations',
    departmentId: 'DEPT-001',
    departmentName: 'Retail',
    headOfCentre: 'Ahmed Al Maktoum',
    isActive: true,
    budgetAllocated: 500000, // AED
  },
  {
    id: 'CC-SUBKO-UAE-002',
    code: 'SUBKO-UAE-MARKETING',
    name: 'Marketing - UAE',
    description: 'Marketing and brand activities for UAE market',
    departmentId: 'DEPT-002',
    departmentName: 'Marketing',
    headOfCentre: 'Sara Khan',
    isActive: true,
    budgetAllocated: 300000, // AED
  },
  // Procinix India Cost Centres
  {
    id: 'CC-PROC-IN-001',
    code: 'PROC-IN-TECH',
    name: 'Technology - Mumbai',
    description: 'Technology development and operations',
    departmentId: 'DEPT-001',
    departmentName: 'Technology',
    headOfCentre: 'Sanjay Verma',
    isActive: true,
    budgetAllocated: 8000000,
  },
  {
    id: 'CC-PROC-IN-002',
    code: 'PROC-IN-CONSULT',
    name: 'Consulting Services',
    description: 'Client consulting and advisory services',
    departmentId: 'DEPT-002',
    departmentName: 'Consulting',
    headOfCentre: 'Meera Iyer',
    isActive: true,
    budgetAllocated: 6000000,
  },
];

// ============================================================================
// MULTI-ENTITY TAX CODES
// ============================================================================

export const MULTI_ENTITY_TAX_CODES: TaxCodeMaster[] = [
  // India GST Codes (applicable for Subko India & Procinix India)
  {
    id: 'TAX-IN-GST18',
    taxCode: 'GST18',
    taxType: 'GST',
    taxName: 'GST @ 18%',
    taxRate: 18,
    isActive: true,
    applicableFrom: '2017-07-01',
    cgstRate: 9,
    sgstRate: 9,
    igstRate: 18,
  },
  {
    id: 'TAX-IN-GST12',
    taxCode: 'GST12',
    taxType: 'GST',
    taxName: 'GST @ 12%',
    taxRate: 12,
    isActive: true,
    applicableFrom: '2017-07-01',
    cgstRate: 6,
    sgstRate: 6,
    igstRate: 12,
  },
  {
    id: 'TAX-IN-GST5',
    taxCode: 'GST5',
    taxType: 'GST',
    taxName: 'GST @ 5%',
    taxRate: 5,
    isActive: true,
    applicableFrom: '2017-07-01',
    cgstRate: 2.5,
    sgstRate: 2.5,
    igstRate: 5,
  },
  {
    id: 'TAX-IN-TDS194C',
    taxCode: 'TDS194C',
    taxType: 'TDS',
    taxName: 'TDS u/s 194C - Contractors',
    taxRate: 2,
    isActive: true,
    applicableFrom: '2020-04-01',
    tdsSection: '194C',
    tdsNature: 'Payments to Contractors',
  },
  {
    id: 'TAX-IN-TDS194J',
    taxCode: 'TDS194J',
    taxType: 'TDS',
    taxName: 'TDS u/s 194J - Professional Services',
    taxRate: 10,
    isActive: true,
    applicableFrom: '2020-04-01',
    tdsSection: '194J',
    tdsNature: 'Professional/Technical Services',
  },
  // UAE VAT Codes (applicable for Subko UAE)
  {
    id: 'TAX-UAE-VAT5',
    taxCode: 'VAT5',
    taxType: 'GST', // Using GST type for compatibility, but represents VAT
    taxName: 'VAT @ 5% (Standard)',
    taxRate: 5,
    isActive: true,
    applicableFrom: '2018-01-01',
  },
  {
    id: 'TAX-UAE-VAT0',
    taxCode: 'VAT0',
    taxType: 'GST',
    taxName: 'VAT @ 0% (Zero-rated)',
    taxRate: 0,
    isActive: true,
    applicableFrom: '2018-01-01',
  },
  {
    id: 'TAX-UAE-EXEMPT',
    taxCode: 'VAT-EXEMPT',
    taxType: 'GST',
    taxName: 'VAT Exempt',
    taxRate: 0,
    isActive: true,
    applicableFrom: '2018-01-01',
  },
];

// ============================================================================
// ENTITY-SCOPED DEPARTMENTS (Dubai / multi-entity)
// ============================================================================

export const MULTI_ENTITY_DEPARTMENTS: DepartmentMaster[] = [
  {
    id: 'DEPT-UAE-001',
    code: 'DEPT-UAE-LOG',
    name: 'Logistics — Dubai',
    description: 'Import, freight and warehouse — UAE entity',
    headOfDepartment: 'UAE Operations Lead',
    isActive: true,
    entityId: 'ENT-SUBKO-UAE',
    entityName: 'Subko Coffee – Dubai',
  },
  {
    id: 'DEPT-UAE-002',
    code: 'DEPT-UAE-OPS',
    name: 'Cafe Operations — Dubai',
    description: 'Retail and cafe operations — UAE',
    headOfDepartment: 'Regional Manager',
    isActive: true,
    entityId: 'ENT-SUBKO-UAE',
    entityName: 'Subko Coffee – Dubai',
  },
];
