import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import {
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Edit2,
  Eye,
  History,
  Plus,
  Search,
  ThumbsDown,
  ThumbsUp,
  Upload,
  X,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { useIncrementalMasterRecords } from '../../hooks/useIncrementalMasterRecords';
import type { MasterKey } from '../../lib/mysql/masterTables';
import { applyMasterApprovalAction } from '../../lib/masters/masterScreenApproval';
import { EntityMappingSelector } from '../shared/EntityMappingSelector';
import type { EntityScopeMapping } from '../../lib/masters/entityMapping';
import { tableHeaderBg, tableHeaderFg } from '../ui/listingStyles';

/**
 * SimpleMasterScreenV2 — config-driven master UI.
 *
 * Renders: listing → full-page Add/Edit/View → audit trail, all inside one
 * component (no route changes needed). Persistence is delegated to
 * `useIncrementalMasterRecords` which auto-saves via PUT /api/masters/<key>
 * on every records mutation; the auto-save pill in the form's sticky topbar
 * reflects that.
 *
 * See docs/FORM_STANDARD_V2.md for the visual contract.
 */

// ── Public types ───────────────────────────────────────────────────────────

export type MasterV2ColumnType = 'text' | 'number' | 'currency' | 'date' | 'badge';
export type MasterV2FieldType = 'text' | 'number' | 'currency' | 'select' | 'textarea' | 'date';
export type SectionStripe = 'teal' | 'blue' | 'amber';

export interface MasterV2Column {
  key: string;
  label: string;
  type?: MasterV2ColumnType;
  fromPayload?: boolean;
  width?: string;
  format?: (value: unknown) => string;
}

export interface MasterV2Field {
  key: string;
  label: string;
  type?: MasterV2FieldType;
  required?: boolean;
  /** UNIVERSAL MASTER RULE: system-generated, never user-editable. Renders
   *  read-only with placeholder "Auto-generated on save" + "Auto" pill. */
  autoGenerated?: boolean;
  fromPayload?: boolean;
  options?: string[];
  /** When provided, replaces `options` with a dynamic {value,label} list. The
   *  field stores `value` to `field.key` and (if `labelKey` is set) `label`
   *  to `field.labelKey` — useful for FK selects like
   *  `departmentId` + `departmentName`. */
  dynamicOptions?: Array<{ value: string; label: string }>;
  /** Companion field key to receive the option label alongside the value. */
  labelKey?: string;
  placeholder?: string;
  helper?: string;
  validate?: (value: unknown, form: MasterV2Record) => string | null;
}

export interface MasterV2SectionRenderContext {
  form: MasterV2Record;
  setForm: (updater: (prev: MasterV2Record) => MasterV2Record) => void;
  readOnly: boolean;
}

export interface MasterV2Section {
  id: string;
  title: string;
  subtitle?: string;
  stripe?: SectionStripe;
  fields: MasterV2Field[];
  /** When provided, replaces the standard 2-column field grid with custom
   *  JSX. Used by masters whose sections need richer composition than a
   *  flat list of MasterV2Field (e.g. an items sub-table inside the form).
   *  The grid spans the full width when this is set. */
  customRender?: (ctx: MasterV2SectionRenderContext) => ReactNode;
}

export interface MasterV2Config {
  title: string;
  subtitle?: string;
  icon: LucideIcon;
  masterKey: MasterKey;
  /** Path used in breadcrumb / audit fetch. Defaults to `/masters/${masterKey}`. */
  apiPath?: string;
  /** Top-level row key used as the record's code. Defaults to `recordCode`. */
  codeKey?: string;
  /** Top-level row key used as the record's name. Defaults to `recordName`. */
  nameKey?: string;
  /** When true, embed the EntityMappingSelector section in the form so the
   *  record can be scoped to one or more entities. */
  entityScoped?: boolean;
  /** When true, View-mode footer shows Approve/Reject buttons that fire
   *  `applyMasterApprovalAction` against the standard master-approval
   *  endpoint. */
  requiresApproval?: boolean;
  /** When true, V2 hides the universal Name input in the Identification
   *  section and skips the "Name is required" validation. Used by masters
   *  whose row shape carries two name fields (e.g. employee_master with
   *  firstName + lastName); the wrapper is responsible for synthesising
   *  `recordName` from the parts when needed. Code remains required. */
  suppressUniversalName?: boolean;
  /** Optional custom synthesiser used when `suppressUniversalName` is true.
   *  Called with the current form on save to compute the value to mirror to
   *  `recordName / name`. Default: leaves recordName untouched. */
  computeRecordName?: (form: MasterV2Record) => string;
  columns: MasterV2Column[];
  formSections: MasterV2Section[];
}

export interface MasterV2Record {
  id?: string;
  code?: string;
  recordCode?: string;
  name?: string;
  recordName?: string;
  status?: string;
  approvalStatus?: string;
  payload?: Record<string, unknown>;
  createdAt?: string;
  updatedAt?: string;
  upload_source?: string;
  uploadSource?: string;
  [key: string]: unknown;
}

type ViewMode = 'list' | 'add' | 'edit' | 'view' | 'audit';
type SaveState = 'idle' | 'saving' | 'saved';

interface Toast {
  id: string;
  tone: 'success' | 'warning' | 'error';
  message: string;
}

// ── Tokens (kept local — Universal Master Rule + V2 spec values) ───────────

const TEAL = '#1D9E75';
const TEAL_DARK = '#0F6E56';
const TEAL_TINT = '#E1F5EE';
const TEAL_SOFT = '#F4FBF8';
const STRIPE_BLUE = '#3C7CB8';
const STRIPE_AMBER = '#BA7517';
const ERROR_RED = '#E24B4A';
const WARN_AMBER = '#BA7517';
const FOG = 'var(--color-border-tertiary)';
const INK = 'var(--color-text-primary)';
const MUTED = 'var(--color-text-secondary)';

const PAGE_BG = 'var(--color-background-primary, #FFFFFF)';
const CARD_RADIUS = 14;

// ── Public component ───────────────────────────────────────────────────────

export function SimpleMasterScreenV2({ config }: { config: MasterV2Config }) {
  const [records, setRecords, isHydrating] = useIncrementalMasterRecords<MasterV2Record>(
    config.masterKey,
    []
  );

  const [viewMode, setViewMode] = useState<ViewMode>('list');
  const [selectedRecord, setSelectedRecord] = useState<MasterV2Record | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'Active' | 'Inactive'>('all');
  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState<10 | 25 | 50>(10);

  const apiPath = config.apiPath ?? `/masters/${config.masterKey}`;
  const codeKey = config.codeKey ?? 'recordCode';
  const nameKey = config.nameKey ?? 'recordName';

  const readCode = useCallback(
    (r: MasterV2Record): string => String(r[codeKey] ?? r.recordCode ?? r.code ?? ''),
    [codeKey]
  );
  const readName = useCallback(
    (r: MasterV2Record): string => String(r[nameKey] ?? r.recordName ?? r.name ?? ''),
    [nameKey]
  );

  // ── Listing filters ──────────────────────────────────────────────────────
  const filtered = useMemo(() => {
    const q = searchTerm.trim().toLowerCase();
    return records.filter((r) => {
      if (
        statusFilter !== 'all' &&
        String(r.status ?? '').toLowerCase() !== statusFilter.toLowerCase()
      ) {
        return false;
      }
      if (!q) return true;
      return readCode(r).toLowerCase().includes(q) || readName(r).toLowerCase().includes(q);
    });
  }, [records, searchTerm, statusFilter, readCode, readName]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const pageRows = filtered.slice(page * pageSize, page * pageSize + pageSize);

  useEffect(() => {
    if (page > totalPages - 1) setPage(0);
  }, [totalPages, page]);

  // ── Navigation between views ─────────────────────────────────────────────
  const openAdd = useCallback(() => {
    setSelectedRecord({ status: 'Active', approvalStatus: 'Draft', payload: {} });
    setViewMode('add');
  }, []);
  const openEdit = useCallback((r: MasterV2Record) => {
    setSelectedRecord(r);
    setViewMode('edit');
  }, []);
  const openView = useCallback((r: MasterV2Record) => {
    setSelectedRecord(r);
    setViewMode('view');
  }, []);
  const openAudit = useCallback((r: MasterV2Record) => {
    setSelectedRecord(r);
    setViewMode('audit');
  }, []);
  const backToList = useCallback(() => {
    setSelectedRecord(null);
    setViewMode('list');
  }, []);

  const handleSave = useCallback(
    (next: MasterV2Record): MasterV2Record => {
      const code = readCode(next);
      const name = readName(next);
      const id = String(next.id ?? code ?? `R-${Date.now()}`);
      const stamped: MasterV2Record = {
        ...next,
        id,
        [codeKey]: code,
        // Maintain the universal recordCode/recordName mirrors so toolbar /
        // listing utilities that don't read the custom keys keep working.
        recordCode: code,
        code,
        [nameKey]: name,
        recordName: name,
        name,
        updatedAt: new Date().toISOString(),
        createdAt: next.createdAt ?? new Date().toISOString(),
      };
      setRecords((current) => {
        const existingIx = current.findIndex((r) => r.id === id);
        if (existingIx >= 0) {
          return current.map((r, i) => (i === existingIx ? stamped : r));
        }
        return [...current, stamped];
      });
      return stamped;
    },
    [setRecords, codeKey, nameKey, readCode, readName]
  );

  const handleDeactivate = useCallback(
    (r: MasterV2Record) => {
      if (!r.id) return;
      setRecords((current) =>
        current.map((row) =>
          row.id === r.id
            ? { ...row, status: 'Inactive', updatedAt: new Date().toISOString() }
            : row
        )
      );
    },
    [setRecords]
  );

  const handleApprovalAction = useCallback(
    async (r: MasterV2Record, action: 'approve' | 'reject', comments = '') => {
      if (!r.id) return;
      try {
        const next = await applyMasterApprovalAction<MasterV2Record>(
          config.masterKey,
          records,
          r.id,
          action,
          comments
        );
        setRecords(next);
      } catch (err) {
        console.error(`[SimpleMasterScreenV2] ${action} failed:`, err);
      }
    },
    [config.masterKey, records, setRecords]
  );

  // ── Render branch ────────────────────────────────────────────────────────
  if (viewMode === 'list') {
    return (
      <ListingView
        config={config}
        apiPath={apiPath}
        codeKey={codeKey}
        nameKey={nameKey}
        records={records}
        filtered={filtered}
        pageRows={pageRows}
        isHydrating={isHydrating}
        searchTerm={searchTerm}
        onSearch={setSearchTerm}
        statusFilter={statusFilter}
        onStatusFilter={setStatusFilter}
        page={page}
        pageSize={pageSize}
        totalPages={totalPages}
        onPageChange={setPage}
        onPageSizeChange={(s) => {
          setPageSize(s);
          setPage(0);
        }}
        onAdd={openAdd}
        onView={openView}
        onEdit={openEdit}
        onAudit={openAudit}
      />
    );
  }

  if (viewMode === 'audit' && selectedRecord) {
    return (
      <AuditView
        config={config}
        apiPath={apiPath}
        codeKey={codeKey}
        nameKey={nameKey}
        record={selectedRecord}
        onBack={backToList}
      />
    );
  }

  if (selectedRecord && (viewMode === 'add' || viewMode === 'edit' || viewMode === 'view')) {
    return (
      <FormView
        key={selectedRecord.id ?? 'new'}
        config={config}
        apiPath={apiPath}
        codeKey={codeKey}
        nameKey={nameKey}
        mode={viewMode}
        initial={selectedRecord}
        onBack={backToList}
        onSave={handleSave}
        onDeactivate={handleDeactivate}
        onApprovalAction={handleApprovalAction}
      />
    );
  }

  return null;
}

// ── Listing view ──────────────────────────────────────────────────────────

interface ListingProps {
  config: MasterV2Config;
  apiPath: string;
  codeKey: string;
  nameKey: string;
  records: MasterV2Record[];
  filtered: MasterV2Record[];
  pageRows: MasterV2Record[];
  isHydrating: boolean;
  searchTerm: string;
  onSearch: (v: string) => void;
  statusFilter: 'all' | 'Active' | 'Inactive';
  onStatusFilter: (v: 'all' | 'Active' | 'Inactive') => void;
  page: number;
  pageSize: number;
  totalPages: number;
  onPageChange: (p: number) => void;
  onPageSizeChange: (s: 10 | 25 | 50) => void;
  onAdd: () => void;
  onView: (r: MasterV2Record) => void;
  onEdit: (r: MasterV2Record) => void;
  onAudit: (r: MasterV2Record) => void;
}

function ListingView({
  config,
  codeKey,
  nameKey,
  records,
  filtered,
  pageRows,
  isHydrating,
  searchTerm,
  onSearch,
  statusFilter,
  onStatusFilter,
  page,
  pageSize,
  totalPages,
  onPageChange,
  onPageSizeChange,
  onAdd,
  onView,
  onEdit,
  onAudit,
}: ListingProps) {
  const Icon = config.icon;

  const handleExport = () => {
    const cols: MasterV2Column[] = [
      { key: codeKey, label: 'Code' },
      { key: nameKey, label: 'Name' },
      ...config.columns,
      { key: 'status', label: 'Status' },
      { key: 'approvalStatus', label: 'Approval' },
    ];
    const header = cols.map((c) => `"${c.label.replace(/"/g, '""')}"`).join(',');
    const lines = filtered.map((r) =>
      cols
        .map((c) => {
          const v = resolveCell(r, c);
          return `"${String(v ?? '').replace(/"/g, '""')}"`;
        })
        .join(',')
    );
    const csv = [header, ...lines].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.masterKey}-${new Date().toISOString().slice(0, 10)}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ minHeight: '100vh', background: PAGE_BG }}>
      {/* Page header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '16px 24px',
          background: '#FFFFFF',
          borderBottom: `0.5px solid ${FOG}`,
          borderLeft: `3px solid ${TEAL}`,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div
            style={{
              width: 36,
              height: 36,
              borderRadius: 8,
              background: TEAL_TINT,
              color: TEAL_DARK,
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Icon size={18} />
          </div>
          <div>
            <h1 style={{ fontSize: 15, fontWeight: 500, color: INK, margin: 0, lineHeight: 1.3 }}>
              {config.title}
            </h1>
            <p style={{ fontSize: 12, color: MUTED, margin: '2px 0 0 0' }}>
              {config.subtitle ?? `${records.length} record${records.length === 1 ? '' : 's'}`}
            </p>
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button type="button" style={secondaryBtn} onClick={() => undefined}>
            <Upload size={14} /> Bulk upload
          </button>
          <button type="button" style={primaryBtn} onClick={onAdd}>
            <Plus size={14} /> Add {config.title.replace(/ Master$/i, '')}
          </button>
        </div>
      </div>

      {/* Toolbar */}
      <div
        style={{
          padding: '8px 24px',
          background: 'var(--color-background-secondary)',
          borderBottom: `0.5px solid ${FOG}`,
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          flexWrap: 'wrap',
        }}
      >
        <div style={{ position: 'relative', flex: 1, minWidth: 240 }}>
          <Search
            size={14}
            style={{
              position: 'absolute',
              left: 12,
              top: '50%',
              transform: 'translateY(-50%)',
              color: MUTED,
            }}
          />
          <input
            type="text"
            placeholder="Search by code or name…"
            value={searchTerm}
            onChange={(e) => onSearch(e.target.value)}
            style={{
              width: '100%',
              height: 32,
              padding: '0 12px 0 34px',
              border: `0.5px solid ${FOG}`,
              borderRadius: 'var(--border-radius-md)',
              fontSize: 12,
              background: '#FFFFFF',
              color: INK,
              outline: 'none',
            }}
          />
        </div>
        <select
          value={statusFilter}
          onChange={(e) => onStatusFilter(e.target.value as 'all' | 'Active' | 'Inactive')}
          style={selectStyle}
        >
          <option value="all">All statuses</option>
          <option value="Active">Active</option>
          <option value="Inactive">Inactive</option>
        </select>
        {config.entityScoped && (
          <select disabled style={{ ...selectStyle, opacity: 0.6 }}>
            <option>All entities</option>
          </select>
        )}
        <button type="button" style={secondaryBtn} onClick={handleExport}>
          Export CSV
        </button>
      </div>

      {/* Table */}
      <div style={{ background: '#FFFFFF' }}>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ background: tableHeaderBg }}>
                <th style={headerCell('80px')}>Code</th>
                <th style={headerCell()}>Name</th>
                {config.columns.map((c) => (
                  <th key={c.key} style={headerCell(c.width)}>
                    {c.label}
                  </th>
                ))}
                <th style={headerCell('110px')}>Status</th>
                <th style={headerCell('130px')}>Approval</th>
                <th style={{ ...headerCell('150px'), textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {isHydrating ? (
                <tr>
                  <td
                    colSpan={5 + config.columns.length}
                    style={{ padding: 32, textAlign: 'center', color: MUTED, fontSize: 12 }}
                  >
                    Loading {config.title.toLowerCase()}…
                  </td>
                </tr>
              ) : pageRows.length === 0 ? (
                <tr>
                  <td
                    colSpan={5 + config.columns.length}
                    style={{ padding: 32, textAlign: 'center', color: MUTED, fontSize: 12 }}
                  >
                    No records match the current filters.
                  </td>
                </tr>
              ) : (
                pageRows.map((r) => (
                  <ListingRow
                    key={String(r.id ?? r[codeKey] ?? r.recordCode ?? r.code ?? Math.random())}
                    record={r}
                    codeKey={codeKey}
                    nameKey={nameKey}
                    columns={config.columns}
                    onView={() => onView(r)}
                    onEdit={() => onEdit(r)}
                    onAudit={() => onAudit(r)}
                  />
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '10px 24px',
            borderTop: `0.5px solid ${FOG}`,
            background: '#FFFFFF',
            fontSize: 12,
            color: MUTED,
          }}
        >
          <div>
            Showing {filtered.length === 0 ? 0 : page * pageSize + 1}–
            {Math.min((page + 1) * pageSize, filtered.length)} of {filtered.length}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span>Rows:</span>
            <select
              value={pageSize}
              onChange={(e) => onPageSizeChange(Number(e.target.value) as 10 | 25 | 50)}
              style={{ ...selectStyle, height: 28 }}
            >
              <option value={10}>10</option>
              <option value={25}>25</option>
              <option value={50}>50</option>
            </select>
            <button
              type="button"
              disabled={page === 0}
              onClick={() => onPageChange(page - 1)}
              style={pagerBtn(page === 0)}
              aria-label="Previous page"
            >
              <ChevronLeft size={14} />
            </button>
            <span>
              Page {page + 1} of {totalPages}
            </span>
            <button
              type="button"
              disabled={page >= totalPages - 1}
              onClick={() => onPageChange(page + 1)}
              style={pagerBtn(page >= totalPages - 1)}
              aria-label="Next page"
            >
              <ChevronRight size={14} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function ListingRow({
  record,
  codeKey,
  nameKey,
  columns,
  onView,
  onEdit,
  onAudit,
}: {
  record: MasterV2Record;
  codeKey: string;
  nameKey: string;
  columns: MasterV2Column[];
  onView: () => void;
  onEdit: () => void;
  onAudit: () => void;
}) {
  const [hover, setHover] = useState(false);
  const code = String(record[codeKey] ?? record.recordCode ?? record.code ?? '');
  const name = String(record[nameKey] ?? record.recordName ?? record.name ?? '');
  return (
    <tr
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        background: hover ? TEAL_SOFT : '#FFFFFF',
        borderBottom: `0.5px solid ${FOG}`,
      }}
    >
      <td style={{ ...rowCell, fontFamily: 'monospace', fontSize: 12 }}>{code || '—'}</td>
      <td style={{ ...rowCell, fontWeight: 500 }}>{name || '—'}</td>
      {columns.map((c) => {
        const v = resolveCell(record, c);
        return (
          <td key={c.key} style={rowCell}>
            {c.format ? c.format(v) : v == null || v === '' ? '—' : String(v)}
          </td>
        );
      })}
      <td style={rowCell}>
        <StatusBadge status={String(record.status ?? '')} />
      </td>
      <td style={rowCell}>
        <ApprovalBadge approval={String(record.approvalStatus ?? '')} />
      </td>
      <td style={{ ...rowCell, textAlign: 'right' }}>
        <div style={{ display: 'inline-flex', gap: 4 }}>
          <IconActionButton tone="teal" title="View" onClick={onView}>
            <Eye size={13} />
          </IconActionButton>
          <IconActionButton tone="blue" title="Edit" onClick={onEdit}>
            <Edit2 size={13} />
          </IconActionButton>
          <IconActionButton tone="amber" title="Audit trail" onClick={onAudit}>
            <History size={13} />
          </IconActionButton>
        </div>
      </td>
    </tr>
  );
}

// ── Form view (Add / Edit / View) ─────────────────────────────────────────

interface FormViewProps {
  config: MasterV2Config;
  apiPath: string;
  codeKey: string;
  nameKey: string;
  mode: 'add' | 'edit' | 'view';
  initial: MasterV2Record;
  onBack: () => void;
  onSave: (record: MasterV2Record) => MasterV2Record;
  onDeactivate: (record: MasterV2Record) => void;
  onApprovalAction: (
    record: MasterV2Record,
    action: 'approve' | 'reject',
    comments?: string
  ) => Promise<void>;
}

function FormView({
  config,
  apiPath,
  codeKey,
  nameKey,
  mode,
  initial,
  onBack,
  onSave,
  onDeactivate,
  onApprovalAction,
}: FormViewProps) {
  const Icon = config.icon;
  const isView = mode === 'view';
  const isEdit = mode === 'edit';
  const isAdd = mode === 'add';
  const readOnly = isView;

  const [form, setForm] = useState<MasterV2Record>(initial);
  const [touched, setTouched] = useState<Set<string>>(new Set());
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [saveState, setSaveState] = useState<SaveState>('idle');
  const [lastSavedAt, setLastSavedAt] = useState<Date | null>(
    initial.updatedAt ? new Date(String(initial.updatedAt)) : null
  );
  const [toasts, setToasts] = useState<Toast[]>([]);

  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const allFields = useMemo(
    () => config.formSections.flatMap((s) => s.fields),
    [config.formSections]
  );

  // ── Toast helpers ────────────────────────────────────────────────────────
  const pushToast = useCallback((tone: Toast['tone'], message: string) => {
    setToasts((cur) => {
      const next = [
        ...cur,
        { id: `t-${Date.now()}-${Math.random().toString(36).slice(2)}`, tone, message },
      ];
      return next.slice(-3);
    });
  }, []);
  const dismissToast = useCallback((id: string) => {
    setToasts((cur) => cur.filter((t) => t.id !== id));
  }, []);
  // Auto-dismiss success toasts after 3s
  useEffect(() => {
    const timers = toasts
      .filter((t) => t.tone === 'success')
      .map((t) =>
        setTimeout(() => {
          setToasts((cur) => cur.filter((x) => x.id !== t.id));
        }, 3000)
      );
    return () => timers.forEach(clearTimeout);
  }, [toasts]);

  // ── Validation ───────────────────────────────────────────────────────────
  const validateField = useCallback(
    (field: MasterV2Field, value: unknown, fullForm: MasterV2Record): string | null => {
      if (field.autoGenerated) return null;
      if (field.required) {
        if (value == null || (typeof value === 'string' && value.trim() === '')) {
          return `${field.label} is required`;
        }
      }
      if (field.validate) return field.validate(value, fullForm);
      return null;
    },
    []
  );

  const validateAll = useCallback((): Record<string, string> => {
    const next: Record<string, string> = {};
    for (const field of allFields) {
      const v = readField(form, field);
      const err = validateField(field, v, form);
      if (err) next[field.key] = err;
    }
    // Code is always required (universal master rule); Name is required
    // unless the master suppresses the universal Name field — in that
    // case the master has its own first/last (or similar) split that
    // V2 has no opinion about, beyond synthesising `recordName` via
    // `config.computeRecordName` at save time for downstream consumers.
    if (!String(form.recordCode ?? form.code ?? '').trim()) {
      next['__code'] = 'Code is required';
    }
    if (!config.suppressUniversalName && !String(form.recordName ?? form.name ?? '').trim()) {
      next['__name'] = 'Name is required';
    }
    return next;
  }, [allFields, form, validateField, config.suppressUniversalName]);

  // ── Field mutation ───────────────────────────────────────────────────────
  const writeField = (field: MasterV2Field, value: unknown) => {
    setForm((prev) => {
      const cast =
        field.type === 'number' || field.type === 'currency'
          ? value === '' || value == null
            ? null
            : Number(value)
          : value;
      if (field.fromPayload) {
        const payload = { ...((prev.payload as Record<string, unknown>) ?? {}) };
        payload[field.key] = cast;
        return { ...prev, payload };
      }
      return { ...prev, [field.key]: cast };
    });
  };

  const writeTop = (key: string, value: unknown) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const onFieldBlur = (field: MasterV2Field) => {
    setTouched((cur) => {
      const next = new Set(cur);
      next.add(field.key);
      return next;
    });
    const err = validateField(field, readField(form, field), form);
    setErrors((cur) => {
      const next = { ...cur };
      if (err) next[field.key] = err;
      else delete next[field.key];
      return next;
    });
    // Auto-save: only in edit mode, only if no validation errors, debounced
    if (isEdit && Object.keys(errors).length === 0 && !err) {
      if (debounceRef.current) clearTimeout(debounceRef.current);
      debounceRef.current = setTimeout(() => {
        setSaveState('saving');
        const saved = onSave(form);
        setLastSavedAt(new Date());
        setSaveState('saved');
        setTimeout(() => setSaveState('idle'), 1200);
        setForm(saved);
      }, 1500);
    }
  };

  // ── Submit handlers ──────────────────────────────────────────────────────
  const submit = (activate: boolean) => {
    const validation = validateAll();
    setErrors(validation);
    if (Object.keys(validation).length > 0) {
      pushToast(
        'error',
        `Fix ${Object.keys(validation).length} validation error${Object.keys(validation).length === 1 ? '' : 's'} before saving.`
      );
      return;
    }
    setSaveState('saving');
    // When this master requires approval, activation goes via the approval
    // queue — flip status to Pending Approval instead of Approved/Active.
    const targetApproval = activate
      ? config.requiresApproval
        ? 'Pending Approval'
        : 'Approved'
      : 'Draft';
    const computedName = config.computeRecordName?.(form);
    const next: MasterV2Record = {
      ...form,
      status: activate ? 'Active' : (form.status ?? 'Active'),
      approvalStatus: targetApproval,
      ...(computedName
        ? { recordName: computedName, name: computedName, [nameKey]: computedName }
        : {}),
    };
    const saved = onSave(next);
    setForm(saved);
    setLastSavedAt(new Date());
    setSaveState('saved');
    pushToast(
      'success',
      activate
        ? config.requiresApproval
          ? 'Submitted for approval.'
          : 'Saved and activated.'
        : 'Draft saved.'
    );
    setTimeout(() => onBack(), 800);
  };

  const handleDeactivate = () => {
    if (!form.id) return;
    if (!window.confirm(`Deactivate "${form.recordName ?? form.name ?? form.id}"?`)) return;
    onDeactivate(form);
    pushToast('warning', 'Record marked Inactive.');
    setTimeout(() => onBack(), 600);
  };

  const codeValue = String(form[codeKey] ?? form.recordCode ?? form.code ?? '');
  const nameValue = String(form[nameKey] ?? form.recordName ?? form.name ?? '');

  return (
    <div
      style={{ minHeight: '100vh', background: PAGE_BG, display: 'flex', flexDirection: 'column' }}
    >
      {/* Sticky topbar */}
      <div
        style={{
          position: 'sticky',
          top: 0,
          zIndex: 20,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 24px',
          background: '#FFFFFF',
          borderBottom: `0.5px solid ${FOG}`,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button
            type="button"
            onClick={onBack}
            style={{
              height: 30,
              padding: '0 10px',
              background: 'transparent',
              border: 'none',
              color: MUTED,
              fontSize: 12,
              cursor: 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: 6,
            }}
          >
            <ArrowLeft size={14} /> Back
          </button>
          <div
            style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: MUTED }}
          >
            <span>Masters</span>
            <ChevronRight size={12} />
            <span>{config.title}</span>
            <ChevronRight size={12} />
            <span style={{ color: INK }}>{isAdd ? 'New' : isEdit ? 'Edit' : 'View'}</span>
          </div>
        </div>
        <AutoSavePill state={saveState} apiPath={apiPath} editing={isEdit} />
      </div>

      {/* Form hero */}
      <div
        style={{
          padding: '20px 24px 16px',
          background: '#FFFFFF',
          borderBottom: `0.5px solid ${FOG}`,
          display: 'flex',
          alignItems: 'flex-start',
          justifyContent: 'space-between',
          gap: 16,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          <div
            style={{
              width: 44,
              height: 44,
              borderRadius: 10,
              background: TEAL_TINT,
              color: TEAL_DARK,
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Icon size={22} />
          </div>
          <div>
            <h1 style={{ fontSize: 17, fontWeight: 500, color: INK, margin: 0 }}>
              {isAdd
                ? `New ${config.title.replace(/ Master$/i, '')}`
                : nameValue || codeValue || config.title}
            </h1>
            <p style={{ fontSize: 12, color: MUTED, margin: '4px 0 0 0' }}>
              {isAdd
                ? 'Fill in the details below. Auto-save activates on first save.'
                : `${config.title} · ${codeValue || '—'}`}
            </p>
          </div>
        </div>
        <StatusBadge status={String(form.status ?? 'Active')} />
      </div>

      {/* Body — single card with section dividers */}
      <div style={{ flex: 1, padding: '20px 24px 96px' }}>
        {/* Toasts (top of form, stacked, max 3) */}
        {toasts.length > 0 && (
          <div style={{ marginBottom: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
            {toasts.map((t) => (
              <ToastBanner key={t.id} toast={t} onDismiss={() => dismissToast(t.id)} />
            ))}
          </div>
        )}

        <div
          style={{
            background: '#FFFFFF',
            border: `0.5px solid ${FOG}`,
            borderRadius: CARD_RADIUS,
            overflow: 'hidden',
          }}
        >
          {/* Universal section — Code + Name always first */}
          <FormSection
            title="Identification"
            subtitle="Code is auto-generated; name identifies the record across the system."
            stripe="teal"
          >
            <FieldRow
              label="Code"
              required
              error={errors['__code']}
              touched={touched.has('__code')}
              autoGenerated
            >
              <ReadOnlyInput
                value={codeValue}
                placeholder={isAdd ? 'Auto-generated on save' : ''}
                ariaLabel="Code (auto-generated)"
              />
              <AutoPill />
            </FieldRow>
            {!config.suppressUniversalName && (
              <FieldRow
                label="Name"
                required
                error={touched.has('__name') ? errors['__name'] : undefined}
                touched={touched.has('__name')}
              >
                <input
                  type="text"
                  value={nameValue}
                  onChange={(e) => {
                    writeTop(nameKey, e.target.value);
                    writeTop('recordName', e.target.value);
                    writeTop('name', e.target.value);
                  }}
                  onBlur={() => {
                    setTouched((cur) => new Set(cur).add('__name'));
                    setErrors((cur) => {
                      const next = { ...cur };
                      if (!String(nameValue).trim()) next['__name'] = 'Name is required';
                      else delete next['__name'];
                      return next;
                    });
                  }}
                  readOnly={readOnly}
                  placeholder="Display name"
                  style={inputStyle(touched.has('__name'), errors['__name'], readOnly)}
                />
                {!errors['__name'] && touched.has('__name') && <ValidIcon />}
              </FieldRow>
            )}
          </FormSection>

          {/* Configured sections */}
          {config.formSections.map((section) => (
            <FormSection
              key={section.id}
              title={section.title}
              subtitle={section.subtitle}
              stripe={section.stripe ?? 'blue'}
              fullWidth={Boolean(section.customRender)}
            >
              {section.customRender
                ? section.customRender({ form, setForm, readOnly })
                : section.fields.map((field) => (
                    <ConfiguredFieldRow
                      key={field.key}
                      field={field}
                      form={form}
                      setForm={setForm}
                      touched={touched.has(field.key)}
                      error={errors[field.key]}
                      readOnly={readOnly}
                      onChange={(v) => writeField(field, v)}
                      onBlur={() => onFieldBlur(field)}
                    />
                  ))}
            </FormSection>
          ))}

          {/* Entity mapping (only when config.entityScoped). Re-uses the
              existing EntityMappingSelector — global vs per-entity scope. */}
          {config.entityScoped && (
            <div style={{ borderTop: `0.5px solid ${FOG}`, padding: '16px 20px 20px' }}>
              <EntityMappingSelector
                value={(form.entityMappings as EntityScopeMapping[] | undefined) ?? []}
                onChange={(mappings) => setForm((prev) => ({ ...prev, entityMappings: mappings }))}
              />
            </div>
          )}

          {/* Always-on bottom section — status / approval */}
          <FormSection title="Status" subtitle="Activation and approval state." stripe="amber">
            <FieldRow label="Status">
              <select
                value={String(form.status ?? 'Active')}
                onChange={(e) => writeTop('status', e.target.value)}
                disabled={readOnly}
                style={inputStyle(false, undefined, readOnly)}
              >
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
              </select>
            </FieldRow>
            <FieldRow label="Approval">
              <select
                value={String(form.approvalStatus ?? 'Draft')}
                onChange={(e) => writeTop('approvalStatus', e.target.value)}
                disabled={readOnly}
                style={inputStyle(false, undefined, readOnly)}
              >
                <option value="Draft">Draft</option>
                <option value="Pending Approval">Pending Approval</option>
                <option value="Approved">Approved</option>
                <option value="Rejected">Rejected</option>
              </select>
            </FieldRow>
          </FormSection>
        </div>
      </div>

      {/* Sticky footer */}
      <div
        style={{
          position: 'sticky',
          bottom: 0,
          zIndex: 10,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 24px',
          background: '#FFFFFF',
          borderTop: `0.5px solid ${FOG}`,
          boxShadow: '0 -4px 12px rgba(0,0,0,0.04)',
        }}
      >
        <div style={{ fontSize: 11, color: MUTED }}>
          {lastSavedAt ? `Last saved ${formatRelative(lastSavedAt)}` : 'Not saved yet'}
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          {isEdit && String(form.status ?? '').toLowerCase() === 'active' && (
            <button type="button" style={ghostRedBtn} onClick={handleDeactivate}>
              Deactivate
            </button>
          )}
          <button type="button" style={secondaryBtn} onClick={onBack}>
            Cancel
          </button>
          {isView && config.requiresApproval && form.approvalStatus === 'Pending Approval' && (
            <>
              <button
                type="button"
                style={ghostRedBtn}
                onClick={async () => {
                  const comments = window.prompt('Reason for rejection (optional)') ?? '';
                  await onApprovalAction(form, 'reject', comments);
                  pushToast('warning', 'Record rejected.');
                  setTimeout(() => onBack(), 600);
                }}
              >
                <ThumbsDown size={14} /> Reject
              </button>
              <button
                type="button"
                style={primaryBtn}
                onClick={async () => {
                  await onApprovalAction(form, 'approve');
                  pushToast('success', 'Record approved.');
                  setTimeout(() => onBack(), 600);
                }}
              >
                <ThumbsUp size={14} /> Approve
              </button>
            </>
          )}
          {!isView && (
            <>
              <button type="button" style={secondaryBtn} onClick={() => submit(false)}>
                Save draft
              </button>
              <button type="button" style={primaryBtn} onClick={() => submit(true)}>
                <CheckCircle2 size={14} />{' '}
                {config.requiresApproval ? 'Save & submit for approval' : 'Save & activate'}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Audit view ─────────────────────────────────────────────────────────────

function AuditView({
  config,
  apiPath,
  codeKey,
  nameKey,
  record,
  onBack,
}: {
  config: MasterV2Config;
  apiPath: string;
  codeKey: string;
  nameKey: string;
  record: MasterV2Record;
  onBack: () => void;
}) {
  const Icon = config.icon;
  // Without a per-master audit-log endpoint, the trail is derived from the
  // record's own metadata: created → updated → current state. Future server
  // work can expand this into a real change-log fetch.
  const entries = useMemo(() => {
    const items: Array<{
      tone: 'teal' | 'blue' | 'amber' | 'grey';
      action: string;
      user: string;
      at: string;
    }> = [];
    const recordName = String(record[nameKey] ?? record.recordName ?? record.name ?? record.id);
    if (record.createdAt) {
      items.push({
        tone: 'teal',
        action: `Record created — ${recordName}`,
        user: String(record.createdBy ?? record.created_by ?? 'System'),
        at: String(record.createdAt),
      });
    }
    if (record.updatedAt && record.updatedAt !== record.createdAt) {
      items.push({
        tone: 'blue',
        action: 'Record updated',
        user: String(record.updatedBy ?? record.updated_by ?? 'System'),
        at: String(record.updatedAt),
      });
    }
    const approval = String(record.approvalStatus ?? '');
    if (approval && approval !== 'Draft') {
      items.push({
        tone: approval === 'Approved' ? 'teal' : approval === 'Rejected' ? 'amber' : 'blue',
        action: `Approval state: ${approval}`,
        user: String(record.approvedBy ?? record.approved_by ?? 'System'),
        at: String(record.approvedAt ?? record.approved_at ?? record.updatedAt ?? ''),
      });
    }
    return items;
  }, [record]);

  return (
    <div
      style={{ minHeight: '100vh', background: PAGE_BG, display: 'flex', flexDirection: 'column' }}
    >
      <div
        style={{
          position: 'sticky',
          top: 0,
          zIndex: 20,
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          padding: '12px 24px',
          background: '#FFFFFF',
          borderBottom: `0.5px solid ${FOG}`,
        }}
      >
        <button
          type="button"
          onClick={onBack}
          style={{
            height: 30,
            padding: '0 10px',
            background: 'transparent',
            border: 'none',
            color: MUTED,
            fontSize: 12,
            cursor: 'pointer',
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
          }}
        >
          <ArrowLeft size={14} /> Back
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: MUTED }}>
          <span>Masters</span>
          <ChevronRight size={12} />
          <span>{config.title}</span>
          <ChevronRight size={12} />
          <span style={{ color: INK }}>Audit trail</span>
        </div>
      </div>

      <div
        style={{
          padding: '20px 24px 16px',
          background: '#FFFFFF',
          borderBottom: `0.5px solid ${FOG}`,
          display: 'flex',
          alignItems: 'center',
          gap: 14,
        }}
      >
        <div
          style={{
            width: 44,
            height: 44,
            borderRadius: 10,
            background: TEAL_TINT,
            color: TEAL_DARK,
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Icon size={22} />
        </div>
        <div>
          <h1 style={{ fontSize: 17, fontWeight: 500, color: INK, margin: 0 }}>
            {String(record[nameKey] ?? record.recordName ?? record.name ?? record.id ?? '—')}
          </h1>
          <p style={{ fontSize: 12, color: MUTED, margin: '4px 0 0 0' }}>
            {apiPath} · {String(record[codeKey] ?? record.recordCode ?? record.code ?? '—')}
          </p>
        </div>
      </div>

      <div style={{ flex: 1, padding: '20px 24px' }}>
        <div
          style={{
            background: '#FFFFFF',
            border: `0.5px solid ${FOG}`,
            borderRadius: CARD_RADIUS,
            padding: 20,
          }}
        >
          {entries.length === 0 ? (
            <p style={{ fontSize: 12, color: MUTED, margin: 0 }}>
              No history available yet for this record.
            </p>
          ) : (
            <ol
              style={{
                margin: 0,
                padding: 0,
                listStyle: 'none',
                display: 'flex',
                flexDirection: 'column',
                gap: 12,
              }}
            >
              {entries.map((e, i) => (
                <li
                  key={i}
                  style={{
                    display: 'flex',
                    gap: 12,
                    alignItems: 'flex-start',
                    paddingBottom: 12,
                    borderBottom: i < entries.length - 1 ? `0.5px solid ${FOG}` : 'none',
                  }}
                >
                  <span
                    style={{
                      width: 30,
                      height: 30,
                      borderRadius: 8,
                      background:
                        e.tone === 'teal'
                          ? TEAL_TINT
                          : e.tone === 'blue'
                            ? '#E6F1FB'
                            : e.tone === 'amber'
                              ? '#FAEEDA'
                              : '#F4F7FB',
                      color:
                        e.tone === 'teal'
                          ? TEAL_DARK
                          : e.tone === 'blue'
                            ? '#0C447C'
                            : e.tone === 'amber'
                              ? '#633806'
                              : '#516173',
                      display: 'inline-flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      flexShrink: 0,
                    }}
                  >
                    <History size={14} />
                  </span>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 13, fontWeight: 500, color: INK }}>{e.action}</div>
                    <div style={{ fontSize: 11, color: MUTED, marginTop: 2 }}>
                      {e.user} · {formatRelative(e.at ? new Date(e.at) : new Date())}
                    </div>
                  </div>
                </li>
              ))}
            </ol>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Small visual helpers ───────────────────────────────────────────────────

function FormSection({
  title,
  subtitle,
  stripe = 'teal',
  fullWidth = false,
  children,
}: {
  title: string;
  subtitle?: string;
  stripe?: SectionStripe;
  fullWidth?: boolean;
  children: ReactNode;
}) {
  const stripeColor = stripe === 'teal' ? TEAL : stripe === 'blue' ? STRIPE_BLUE : STRIPE_AMBER;
  return (
    <div style={{ borderTop: `0.5px solid ${FOG}` }}>
      <div
        style={{
          display: 'flex',
          alignItems: 'flex-start',
          gap: 10,
          padding: '16px 20px 12px',
          borderLeft: `3px solid ${stripeColor}`,
          marginLeft: -1,
        }}
      >
        <div>
          <div style={{ fontSize: 13, fontWeight: 600, color: INK }}>{title}</div>
          {subtitle && <div style={{ fontSize: 11, color: MUTED, marginTop: 2 }}>{subtitle}</div>}
        </div>
      </div>
      <div
        style={
          fullWidth
            ? { padding: '0 20px 20px' }
            : {
                display: 'grid',
                gridTemplateColumns: '1fr 1fr',
                gap: 16,
                padding: '0 20px 20px',
              }
        }
      >
        {children}
      </div>
    </div>
  );
}

function FieldRow({
  label,
  required,
  error,
  touched,
  autoGenerated,
  children,
}: {
  label: string;
  required?: boolean;
  error?: string;
  touched?: boolean;
  autoGenerated?: boolean;
  children: ReactNode;
}) {
  return (
    <div>
      <label
        style={{
          display: 'block',
          fontSize: 11,
          color: MUTED,
          marginBottom: 6,
          fontWeight: 500,
        }}
      >
        {label}
        {required && <span style={{ color: ERROR_RED, marginLeft: 4 }}>*</span>}
        {autoGenerated && (
          <span style={{ color: MUTED, marginLeft: 6, fontSize: 10 }}>(system-generated)</span>
        )}
      </label>
      <div style={{ position: 'relative', display: 'flex', alignItems: 'center', gap: 6 }}>
        {children}
      </div>
      {error && touched && (
        <div
          style={{
            marginTop: 4,
            fontSize: 11,
            color: ERROR_RED,
            display: 'flex',
            alignItems: 'center',
            gap: 4,
          }}
        >
          <AlertCircle size={11} /> {error}
        </div>
      )}
    </div>
  );
}

function ConfiguredFieldRow({
  field,
  form,
  touched,
  error,
  readOnly,
  onChange,
  onBlur,
  setForm,
}: {
  field: MasterV2Field;
  form: MasterV2Record;
  touched: boolean;
  error?: string;
  readOnly: boolean;
  onChange: (v: unknown) => void;
  onBlur: () => void;
  setForm: (updater: (prev: MasterV2Record) => MasterV2Record) => void;
}) {
  const value = readField(form, field);
  const stringValue = value == null ? '' : String(value);
  const isAuto = field.autoGenerated === true;
  const effectiveReadOnly = readOnly || isAuto;

  if (isAuto) {
    return (
      <FieldRow label={field.label} autoGenerated>
        <ReadOnlyInput
          value={stringValue}
          placeholder={stringValue ? '' : 'Auto-generated on save'}
          ariaLabel={`${field.label} (auto-generated)`}
        />
        <AutoPill />
      </FieldRow>
    );
  }

  let control: ReactNode;
  if (field.type === 'select' && field.dynamicOptions) {
    const handleDynamicChange = (newId: string) => {
      const matched = field.dynamicOptions?.find((o) => o.value === newId);
      const label = matched?.label ?? '';
      if (field.labelKey) {
        setForm((prev) => ({ ...prev, [field.key]: newId, [field.labelKey as string]: label }));
      } else {
        onChange(newId);
      }
    };
    control = (
      <select
        value={stringValue}
        onChange={(e) => handleDynamicChange(e.target.value)}
        onBlur={onBlur}
        disabled={effectiveReadOnly}
        style={inputStyle(touched, error, effectiveReadOnly)}
      >
        <option value="">Select…</option>
        {field.dynamicOptions.map((o) => (
          <option key={o.value} value={o.value}>
            {o.label}
          </option>
        ))}
      </select>
    );
  } else if (field.type === 'select' && field.options) {
    control = (
      <select
        value={stringValue}
        onChange={(e) => onChange(e.target.value)}
        onBlur={onBlur}
        disabled={effectiveReadOnly}
        style={inputStyle(touched, error, effectiveReadOnly)}
      >
        <option value="">Select…</option>
        {field.options.map((o) => (
          <option key={o} value={o}>
            {o}
          </option>
        ))}
      </select>
    );
  } else if (field.type === 'textarea') {
    control = (
      <textarea
        value={stringValue}
        onChange={(e) => onChange(e.target.value)}
        onBlur={onBlur}
        readOnly={effectiveReadOnly}
        placeholder={field.placeholder}
        rows={2}
        style={{
          ...inputStyle(touched, error, effectiveReadOnly),
          minHeight: 64,
          resize: 'vertical',
        }}
      />
    );
  } else {
    control = (
      <input
        type={
          field.type === 'date'
            ? 'date'
            : field.type === 'number' || field.type === 'currency'
              ? 'number'
              : 'text'
        }
        value={stringValue}
        onChange={(e) => onChange(e.target.value)}
        onBlur={onBlur}
        readOnly={effectiveReadOnly}
        placeholder={field.placeholder}
        style={inputStyle(touched, error, effectiveReadOnly)}
      />
    );
  }

  return (
    <FieldRow label={field.label} required={field.required} error={error} touched={touched}>
      {control}
      {!error && touched && stringValue && <ValidIcon />}
    </FieldRow>
  );
}

function ValidIcon() {
  return (
    <span style={{ position: 'absolute', right: 8, color: TEAL_DARK, pointerEvents: 'none' }}>
      <CheckCircle2 size={14} />
    </span>
  );
}

function AutoPill() {
  return (
    <span
      style={{
        padding: '3px 8px',
        background: '#F1EFE8',
        color: '#5F5E5A',
        fontSize: 10,
        fontWeight: 500,
        borderRadius: 20,
        whiteSpace: 'nowrap',
      }}
    >
      Auto
    </span>
  );
}

function ReadOnlyInput({
  value,
  placeholder,
  ariaLabel,
}: {
  value: string;
  placeholder?: string;
  ariaLabel?: string;
}) {
  return (
    <input
      type="text"
      value={value}
      readOnly
      placeholder={placeholder}
      aria-label={ariaLabel}
      style={inputStyle(false, undefined, true)}
    />
  );
}

function AutoSavePill({
  state,
  apiPath,
  editing,
}: {
  state: SaveState;
  apiPath: string;
  editing: boolean;
}) {
  let label = editing ? 'Auto-save enabled' : 'View only';
  let bg = TEAL_TINT;
  let fg = TEAL_DARK;
  if (state === 'saving') {
    label = 'Saving…';
    bg = '#FAEEDA';
    fg = WARN_AMBER;
  } else if (state === 'saved') {
    label = 'Saved just now';
    bg = TEAL_TINT;
    fg = TEAL_DARK;
  }
  return (
    <span
      title={`PUT ${apiPath}`}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        padding: '4px 10px',
        background: bg,
        color: fg,
        borderRadius: 20,
        fontSize: 11,
        fontWeight: 500,
      }}
    >
      <span
        style={{
          width: 6,
          height: 6,
          borderRadius: 6,
          background: fg,
          display: 'inline-block',
        }}
      />
      {label}
    </span>
  );
}

function ToastBanner({ toast, onDismiss }: { toast: Toast; onDismiss: () => void }) {
  const tone = toast.tone;
  const bg = tone === 'success' ? TEAL_TINT : tone === 'warning' ? '#FAEEDA' : '#FCEBEB';
  const fg = tone === 'success' ? TEAL_DARK : tone === 'warning' ? '#633806' : '#791F1F';
  const border = tone === 'success' ? '#5DCAA5' : tone === 'warning' ? '#E1B964' : '#F09595';
  return (
    <div
      role="status"
      style={{
        padding: '10px 14px',
        background: bg,
        color: fg,
        border: `0.5px solid ${border}`,
        borderRadius: 8,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
        fontSize: 12,
      }}
    >
      <span>{toast.message}</span>
      <button
        type="button"
        onClick={onDismiss}
        aria-label="Dismiss"
        style={{
          background: 'transparent',
          border: 'none',
          color: fg,
          cursor: 'pointer',
          padding: 4,
        }}
      >
        <X size={12} />
      </button>
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const active = status.toLowerCase() === 'active';
  return (
    <span
      style={{
        padding: '3px 10px',
        borderRadius: 20,
        fontSize: 11,
        fontWeight: 500,
        background: active ? TEAL_TINT : '#F4F7FB',
        color: active ? TEAL_DARK : '#516173',
        whiteSpace: 'nowrap',
      }}
    >
      {status || 'Active'}
    </span>
  );
}

function ApprovalBadge({ approval }: { approval: string }) {
  const a = approval.toLowerCase();
  let bg = '#F4F7FB';
  let fg = '#516173';
  if (a === 'approved') {
    bg = TEAL_TINT;
    fg = TEAL_DARK;
  } else if (a.includes('pending')) {
    bg = '#FAEEDA';
    fg = '#633806';
  } else if (a === 'rejected') {
    bg = '#FCEBEB';
    fg = '#791F1F';
  }
  return (
    <span
      style={{
        padding: '3px 10px',
        borderRadius: 20,
        fontSize: 11,
        fontWeight: 500,
        background: bg,
        color: fg,
        whiteSpace: 'nowrap',
      }}
    >
      {approval || 'Draft'}
    </span>
  );
}

function IconActionButton({
  tone,
  title,
  children,
  onClick,
}: {
  tone: 'teal' | 'blue' | 'amber';
  title: string;
  children: ReactNode;
  onClick: () => void;
}) {
  const [hover, setHover] = useState(false);
  const hoverBg = tone === 'teal' ? TEAL_TINT : tone === 'blue' ? '#E6F1FB' : '#FAEEDA';
  const hoverFg = tone === 'teal' ? TEAL_DARK : tone === 'blue' ? '#0C447C' : '#633806';
  return (
    <button
      type="button"
      title={title}
      onClick={onClick}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        width: 26,
        height: 26,
        background: hover ? hoverBg : 'transparent',
        color: hover ? hoverFg : MUTED,
        border: '0.5px solid var(--color-border-tertiary)',
        borderRadius: 4,
        cursor: 'pointer',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'background 0.15s, color 0.15s',
      }}
    >
      {children}
    </button>
  );
}

// ── Style tokens ───────────────────────────────────────────────────────────

const primaryBtn: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: 6,
  height: 32,
  padding: '0 14px',
  background: TEAL_DARK,
  color: '#FFFFFF',
  border: 'none',
  borderRadius: 'var(--border-radius-md)',
  fontSize: 12,
  fontWeight: 500,
  cursor: 'pointer',
};

const secondaryBtn: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: 6,
  height: 32,
  padding: '0 12px',
  background: '#FFFFFF',
  color: INK,
  border: `0.5px solid ${FOG}`,
  borderRadius: 'var(--border-radius-md)',
  fontSize: 12,
  cursor: 'pointer',
};

const ghostRedBtn: CSSProperties = {
  ...secondaryBtn,
  color: '#A32D2D',
  borderColor: '#F09595',
};

const selectStyle: CSSProperties = {
  height: 32,
  padding: '0 12px',
  border: `0.5px solid ${FOG}`,
  borderRadius: 'var(--border-radius-md)',
  background: '#FFFFFF',
  color: INK,
  fontSize: 12,
  cursor: 'pointer',
};

function headerCell(width?: string): CSSProperties {
  return {
    padding: '10px 16px',
    fontSize: 11,
    fontWeight: 500,
    color: tableHeaderFg,
    background: tableHeaderBg,
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    width,
    whiteSpace: 'nowrap',
  };
}

const rowCell: CSSProperties = {
  padding: '12px 16px',
  fontSize: 13,
  color: INK,
  verticalAlign: 'middle',
};

function pagerBtn(disabled: boolean): CSSProperties {
  return {
    width: 26,
    height: 26,
    border: `0.5px solid ${FOG}`,
    borderRadius: 4,
    background: '#FFFFFF',
    color: disabled ? '#C7CCD1' : INK,
    cursor: disabled ? 'not-allowed' : 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  };
}

function inputStyle(touched: boolean, error: string | undefined, readOnly: boolean): CSSProperties {
  const hasError = touched && !!error;
  const validGreen = touched && !error;
  return {
    width: '100%',
    height: 36,
    padding: '0 12px',
    border: hasError
      ? `1.5px solid ${ERROR_RED}`
      : validGreen
        ? `1.5px solid ${TEAL}`
        : `0.5px solid ${FOG}`,
    borderRadius: 'var(--border-radius-md)',
    fontSize: 13,
    background: readOnly ? '#F4F7FB' : '#FFFFFF',
    color: INK,
    outline: 'none',
    transition: 'border-color 0.15s',
  };
}

// ── Helpers ────────────────────────────────────────────────────────────────

function resolveCell(record: MasterV2Record, col: MasterV2Column): unknown {
  if (col.fromPayload) {
    const payload = (record.payload as Record<string, unknown>) ?? {};
    return payload[col.key];
  }
  return record[col.key];
}

function readField(record: MasterV2Record, field: MasterV2Field): unknown {
  if (field.fromPayload) {
    const payload = (record.payload as Record<string, unknown>) ?? {};
    return payload[field.key];
  }
  return record[field.key];
}

function formatRelative(d: Date): string {
  const now = Date.now();
  const diff = now - d.getTime();
  if (diff < 0) return d.toLocaleString('en-IN');
  if (diff < 60 * 1000) return 'just now';
  if (diff < 60 * 60 * 1000) return `${Math.floor(diff / 60000)} min ago`;
  if (diff < 24 * 60 * 60 * 1000) return `${Math.floor(diff / 3600000)} hr ago`;
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}
