/**
 * Master Bulk Upload — schema registry.
 *
 * Each entry describes the canonical field shape of a master so the bulk-upload
 * pipeline (identifier/parser/validator) can map uploaded spreadsheet columns
 * to the master's TypeScript interface, validate rows, and enforce
 * prerequisite master dependencies.
 *
 * Notes:
 * - masterKey values MUST match MASTER_KEYS in src/lib/mysql/masterTables.ts.
 * - Field `key` values mirror the TS interface fields defined on each master
 *   component (e.g. EmployeeMaster.tsx -> interface Employee).
 * - Aliases are lowercased, trimmed, single-spaced, punctuation-stripped.
 * - Required fields appear FIRST in each `fields` array, then optional fields.
 * - primaryCodeField is the field used for duplicate detection.
 */

import type { MasterKey } from '../mysql/masterTables';
import type { MasterSchema, MasterSchemaRegistry } from './bulkUploadTypes';

// ---------------------------------------------------------------------------
// Top-level masters (no prerequisites)
// ---------------------------------------------------------------------------

const category_master: MasterSchema = {
  masterKey: 'category_master',
  displayName: 'Category Master',
  description: 'Product / item categories with optional parent hierarchy.',
  headerSignature: ['category code', 'category name', 'parent category'],
  primaryCodeField: 'categoryCode',
  prerequisites: [],
  fields: [
    {
      key: 'categoryCode',
      label: 'Category Code',
      required: true,
      type: 'string',
      aliases: ['category code', 'categorycode', 'cat code', 'code', 'category id'],
    },
    {
      key: 'categoryName',
      label: 'Category Name',
      required: true,
      type: 'string',
      aliases: ['category name', 'categoryname', 'cat name', 'name'],
    },
    {
      key: 'parentCategory',
      label: 'Parent Category',
      required: false,
      type: 'string',
      aliases: ['parent category', 'parent', 'parent cat', 'parentcategory', 'parent code'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'desc', 'details', 'remarks', 'notes'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const country_master: MasterSchema = {
  masterKey: 'country_master',
  displayName: 'Country Master',
  description: 'Countries with ISO code and default currency.',
  headerSignature: ['country code', 'country name', 'iso code'],
  primaryCodeField: 'countryCode',
  prerequisites: [],
  fields: [
    {
      key: 'countryCode',
      label: 'Country Code',
      required: true,
      type: 'string',
      aliases: ['country code', 'iso code', 'iso2', 'country iso', 'countrycode', 'code'],
    },
    {
      key: 'countryName',
      label: 'Country Name',
      required: true,
      type: 'string',
      aliases: ['country name', 'country', 'name', 'countryname'],
    },
    {
      key: 'currency',
      label: 'Currency',
      required: false,
      type: 'string',
      aliases: ['currency', 'currency code', 'default currency', 'iso currency', 'curr'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const department_master: MasterSchema = {
  masterKey: 'department_master',
  displayName: 'Department Master',
  description: 'Organizational departments with head-of-department assignment.',
  headerSignature: ['dept code', 'department code', 'head of dept'],
  primaryCodeField: 'deptCode',
  prerequisites: [],
  fields: [
    {
      key: 'deptCode',
      label: 'Department Code',
      required: true,
      type: 'string',
      aliases: ['dept code', 'department code', 'deptcode', 'dept id', 'department id', 'code'],
    },
    {
      key: 'deptName',
      label: 'Department Name',
      required: true,
      type: 'string',
      aliases: ['dept name', 'department name', 'name', 'deptname', 'department'],
    },
    {
      key: 'headOfDept',
      label: 'Head of Department',
      required: false,
      type: 'string',
      aliases: ['head of department', 'head of dept', 'hod', 'manager', 'head', 'dept head'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const tax_code_master: MasterSchema = {
  masterKey: 'tax_code_master',
  displayName: 'Tax Code Master',
  description: 'Tax codes (GST / VAT / TDS) with effective rates.',
  headerSignature: ['tax code', 'tax rate', 'tax description'],
  primaryCodeField: 'taxCode',
  prerequisites: [],
  fields: [
    {
      key: 'taxCode',
      label: 'Tax Code',
      required: true,
      type: 'string',
      aliases: ['tax code', 'taxcode', 'code', 'gst code', 'vat code'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'tax description', 'desc', 'tax name', 'name'],
    },
    {
      key: 'taxRate',
      label: 'Tax Rate',
      required: false,
      type: 'number',
      aliases: ['tax rate', 'rate', 'percentage', 'percent', 'tax percent', 'gst rate'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const item_category_master: MasterSchema = {
  masterKey: 'item_category_master',
  displayName: 'Item Category Master',
  description: 'Item categories used for classifying procurement items.',
  headerSignature: ['item category code', 'item category', 'category description'],
  primaryCodeField: 'code',
  prerequisites: [],
  fields: [
    {
      key: 'code',
      label: 'Item Category Code',
      required: true,
      type: 'string',
      aliases: ['item category code', 'code', 'category code', 'itemcategorycode', 'cat code'],
    },
    {
      key: 'name',
      label: 'Item Category Name',
      required: true,
      type: 'string',
      aliases: ['item category name', 'name', 'category name', 'item category', 'cat name'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'desc', 'details', 'remarks', 'notes'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const vendor_payment_terms_master: MasterSchema = {
  masterKey: 'vendor_payment_terms_master',
  displayName: 'Vendor Payment Terms Master',
  description: 'Standard vendor payment terms with credit days.',
  headerSignature: ['payment term', 'credit days', 'term code'],
  primaryCodeField: 'code',
  prerequisites: [],
  fields: [
    {
      key: 'code',
      label: 'Payment Term Code',
      required: true,
      type: 'string',
      aliases: ['payment term code', 'term code', 'code', 'payment code', 'pt code'],
    },
    {
      key: 'description',
      label: 'Description',
      required: true,
      type: 'string',
      aliases: ['description', 'payment term', 'term description', 'desc', 'name'],
    },
    {
      key: 'creditDays',
      label: 'Credit Days',
      required: true,
      type: 'integer',
      aliases: ['credit days', 'creditdays', 'days', 'credit period', 'net days', 'payment days'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

// Renamed from `product_master` → `item_master` (2026-05-10): the bulk-upload
// "Item Master" sheet must land in the `item_master.item_master` table that
// /api/items reads, not the legacy `product_master.product_master` canonical
// table. The variable name follows the new masterKey for grep-ability.
const item_master: MasterSchema = {
  masterKey: 'item_master',
  displayName: 'Item Master',
  description:
    'Product and service catalog with classification, pricing, tax, and physical attributes.',
  headerSignature: ['item code', 'item name', 'hsn sac code'],
  primaryCodeField: 'itemCode',
  prerequisites: [],
  fields: [
    // --- Identification ---
    {
      key: 'itemCode',
      label: 'Item Code',
      required: true,
      type: 'string',
      aliases: ['item code', 'itemcode', 'product code', 'code', 'prod code', 'sku code'],
    },
    {
      key: 'itemName',
      label: 'Item Name',
      required: true,
      type: 'string',
      aliases: ['item name', 'itemname', 'product name', 'name', 'prod name', 'product'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'desc', 'item description', 'product description', 'details'],
    },

    // --- Classification ---
    {
      key: 'category',
      label: 'Category',
      required: false,
      type: 'string',
      aliases: ['category', 'item category', 'product category', 'cat'],
    },
    {
      key: 'subCategory',
      label: 'Sub Category',
      required: false,
      type: 'string',
      aliases: ['sub category', 'subcategory', 'sub cat', 'sub-category'],
    },
    {
      key: 'hsnSacCode',
      label: 'HSN/SAC Code',
      required: false,
      type: 'string',
      aliases: ['hsn sac code', 'hsn code', 'sac code', 'hsn', 'sac', 'hsn sac', 'tax code'],
    },
    {
      key: 'uom',
      label: 'UOM',
      required: false,
      type: 'string',
      aliases: ['uom', 'unit of measure', 'unit', 'unit of measurement'],
      foreignKey: { refMaster: 'uom_master', refField: 'code', strict: false },
    },

    // --- Pricing & Tax ---
    {
      key: 'basePrice',
      label: 'Base Price',
      required: false,
      type: 'number',
      aliases: ['base price', 'price', 'unit price', 'rate', 'cost'],
    },
    {
      key: 'currency',
      label: 'Currency',
      required: false,
      type: 'string',
      aliases: ['currency', 'currency code', 'curr'],
      defaultValue: 'INR',
    },
    {
      key: 'taxRate',
      label: 'Tax Rate %',
      required: false,
      type: 'number',
      aliases: ['tax rate', 'rate', 'gst rate', 'tax percent', 'percentage', 'tax rate %'],
    },
    {
      key: 'taxType',
      label: 'Tax Type',
      required: false,
      type: 'enum',
      enumValues: ['GST', 'VAT', 'None'],
      aliases: ['tax type', 'tax category', 'tax kind', 'tax regime'],
    },

    // --- Attributes ---
    {
      key: 'brand',
      label: 'Brand',
      required: false,
      type: 'string',
      aliases: ['brand', 'brand name', 'manufacturer'],
    },
    {
      key: 'material',
      label: 'Material',
      required: false,
      type: 'string',
      aliases: ['material', 'material type', 'composition'],
    },
    {
      key: 'weight',
      label: 'Weight',
      required: false,
      type: 'number',
      aliases: ['weight', 'net weight', 'gross weight', 'wt'],
    },
    {
      key: 'dimensions',
      label: 'Dimensions',
      required: false,
      type: 'string',
      aliases: ['dimensions', 'size', 'dim', 'lxwxh'],
    },

    // --- Status ---
    {
      key: 'status',
      label: 'Status',
      required: true,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const uom_master: MasterSchema = {
  masterKey: 'uom_master',
  displayName: 'Unit of Measure Master',
  description: 'Units of measure used for items and transactions.',
  headerSignature: ['uom code', 'unit of measure', 'uom name'],
  primaryCodeField: 'code',
  prerequisites: [],
  fields: [
    {
      key: 'code',
      label: 'UOM Code',
      required: true,
      type: 'string',
      aliases: ['uom code', 'unit code', 'code', 'uomcode', 'unit'],
    },
    {
      key: 'name',
      label: 'UOM Name',
      required: true,
      type: 'string',
      aliases: ['uom name', 'unit name', 'name', 'unit of measure', 'uomname'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'desc', 'details', 'remarks'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const debit_note_reason_master: MasterSchema = {
  masterKey: 'debit_note_reason_master',
  displayName: 'Debit Note Reason Master',
  description: 'Standard reasons used when issuing vendor debit notes.',
  headerSignature: ['debit note reason', 'reason code', 'reason name'],
  primaryCodeField: 'code',
  prerequisites: [],
  fields: [
    {
      key: 'code',
      label: 'Reason Code',
      required: true,
      type: 'string',
      aliases: ['reason code', 'code', 'debit note reason code', 'dn reason code'],
    },
    {
      key: 'name',
      label: 'Reason Name',
      required: true,
      type: 'string',
      aliases: ['reason name', 'name', 'reason', 'debit note reason', 'dn reason'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'desc', 'details', 'remarks', 'notes'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const cost_centre_master: MasterSchema = {
  masterKey: 'cost_centre_master',
  displayName: 'Cost Centre Master',
  description: 'Cost centres with department mapping and budget limits.',
  headerSignature: ['cost centre code', 'cost center code', 'budget limit'],
  primaryCodeField: 'costCentreCode',
  prerequisites: [],
  fields: [
    {
      key: 'costCentreCode',
      label: 'Cost Centre Code',
      required: true,
      type: 'string',
      aliases: ['cost centre code', 'cost center code', 'cc code', 'costcentrecode', 'code'],
    },
    {
      key: 'costCentreName',
      label: 'Cost Centre Name',
      required: true,
      type: 'string',
      aliases: ['cost centre name', 'cost center name', 'cc name', 'name', 'costcentrename'],
    },
    {
      key: 'department',
      label: 'Department',
      required: false,
      type: 'string',
      aliases: ['department', 'dept', 'department name', 'dept name'],
    },
    {
      key: 'manager',
      label: 'Manager',
      required: false,
      type: 'string',
      aliases: ['manager', 'cc manager', 'head', 'owner', 'incharge'],
    },
    {
      key: 'budgetLimit',
      label: 'Budget Limit',
      required: false,
      type: 'number',
      aliases: ['budget limit', 'budget', 'limit', 'budgetlimit', 'allocated budget'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const profit_centre_master: MasterSchema = {
  masterKey: 'profit_centre_master',
  displayName: 'Profit Centre Master',
  description: 'Profit centres with revenue targets and regional ownership.',
  headerSignature: ['profit centre code', 'profit center code', 'revenue target'],
  primaryCodeField: 'profitCentreCode',
  prerequisites: [],
  fields: [
    {
      key: 'profitCentreCode',
      label: 'Profit Centre Code',
      required: true,
      type: 'string',
      aliases: ['profit centre code', 'profit center code', 'pc code', 'profitcentrecode', 'code'],
    },
    {
      key: 'profitCentreName',
      label: 'Profit Centre Name',
      required: true,
      type: 'string',
      aliases: ['profit centre name', 'profit center name', 'pc name', 'name', 'profitcentrename'],
    },
    {
      key: 'department',
      label: 'Department',
      required: false,
      type: 'string',
      aliases: ['department', 'dept', 'department name', 'dept name'],
    },
    {
      key: 'headOfPC',
      label: 'Head of Profit Centre',
      required: false,
      type: 'string',
      aliases: ['head of pc', 'head of profit centre', 'head', 'pc head', 'owner', 'manager'],
    },
    {
      key: 'revenueTarget',
      label: 'Revenue Target',
      required: false,
      type: 'number',
      aliases: ['revenue target', 'target', 'revenuetarget', 'sales target', 'annual target'],
    },
    {
      key: 'region',
      label: 'Region',
      required: false,
      type: 'string',
      aliases: ['region', 'area', 'zone', 'territory', 'geography'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const roles_master: MasterSchema = {
  masterKey: 'roles_master',
  displayName: 'Roles Master',
  description: 'Application roles used for user access control.',
  headerSignature: ['role code', 'role name', 'permissions'],
  primaryCodeField: 'roleCode',
  prerequisites: [],
  fields: [
    {
      key: 'roleCode',
      label: 'Role Code',
      required: true,
      type: 'string',
      aliases: ['role code', 'rolecode', 'code', 'role id', 'roleid'],
    },
    {
      key: 'roleName',
      label: 'Role Name',
      required: true,
      type: 'string',
      aliases: ['role name', 'rolename', 'name', 'role'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'desc', 'details', 'remarks', 'notes'],
    },
    {
      key: 'permissions',
      label: 'Permissions',
      required: false,
      type: 'string',
      aliases: ['permissions', 'perms', 'privileges', 'access', 'rights'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive', 'Pending Approval'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const currency_master: MasterSchema = {
  masterKey: 'currency_master',
  displayName: 'Currency Master',
  description: 'ISO currencies with symbol, precision, and base-currency flag.',
  headerSignature: ['currency code', 'currency symbol', 'decimal precision'],
  primaryCodeField: 'code',
  prerequisites: [],
  fields: [
    {
      key: 'code',
      label: 'Currency Code',
      required: true,
      type: 'string',
      aliases: ['currency code', 'code', 'iso code', 'curr code', 'ccy'],
    },
    {
      key: 'name',
      label: 'Currency Name',
      required: true,
      type: 'string',
      aliases: ['currency name', 'name', 'curr name', 'currency'],
    },
    {
      key: 'symbol',
      label: 'Symbol',
      required: false,
      type: 'string',
      aliases: ['symbol', 'currency symbol', 'sign', 'ccy symbol'],
    },
    {
      key: 'decimalPrecision',
      label: 'Decimal Precision',
      required: false,
      type: 'integer',
      aliases: ['decimal precision', 'precision', 'decimals', 'decimal places', 'scale'],
      defaultValue: 2,
    },
    {
      key: 'isBaseCurrency',
      label: 'Is Base Currency',
      required: false,
      type: 'boolean',
      aliases: ['is base currency', 'base currency', 'base', 'isbase', 'default currency'],
      defaultValue: false,
    },
    {
      key: 'isActive',
      label: 'Is Active',
      required: false,
      type: 'boolean',
      aliases: ['is active', 'active', 'status', 'enabled'],
      defaultValue: true,
    },
  ],
};

const entity_master: MasterSchema = {
  masterKey: 'entity_master',
  displayName: 'Entity Master',
  description: 'Legal entities / branches with country, currency, and tax regime.',
  headerSignature: ['entity code', 'legal name', 'tax regime'],
  primaryCodeField: 'code',
  prerequisites: [],
  fields: [
    {
      key: 'code',
      label: 'Entity Code',
      required: true,
      type: 'string',
      aliases: ['entity code', 'code', 'entitycode', 'entity id', 'legal entity code'],
    },
    {
      key: 'legalName',
      label: 'Legal Name',
      required: true,
      type: 'string',
      aliases: [
        'legal name',
        'legalname',
        'entity legal name',
        'company legal name',
        'registered name',
      ],
    },
    {
      key: 'name',
      label: 'Entity Name',
      required: false,
      type: 'string',
      aliases: ['entity name', 'name', 'short name', 'display name', 'company name'],
    },
    {
      key: 'region',
      label: 'Region',
      required: false,
      type: 'enum',
      enumValues: ['GCC', 'India', 'South East Asia'],
      aliases: ['region', 'entity region', 'business region', 'market region'],
      defaultValue: 'India',
    },
    {
      key: 'country',
      label: 'Country',
      required: false,
      type: 'string',
      aliases: ['country', 'country name', 'country code', 'home country'],
    },
    {
      key: 'currency',
      label: 'Currency',
      required: false,
      type: 'string',
      aliases: ['currency', 'currency code', 'base currency', 'functional currency'],
    },
    {
      key: 'taxRegime',
      label: 'Tax Regime',
      required: false,
      type: 'enum',
      enumValues: ['GST', 'VAT', 'None'],
      aliases: ['tax regime', 'taxregime', 'tax system', 'tax type', 'regime'],
      defaultValue: 'GST',
    },
    {
      key: 'legalEntityType',
      label: 'Legal Entity Type',
      required: false,
      type: 'enum',
      enumValues: [
        'Pvt Ltd',
        'Public Ltd',
        'LLP',
        'Partnership',
        'Sole Proprietor',
        'Trust',
        'Society',
        'NGO',
        'Government Body',
      ],
      aliases: ['legal entity type', 'entity type', 'company type', 'business type', 'org type'],
    },
    {
      key: 'businessLicenseNumber',
      label: 'Business License Number',
      required: false,
      type: 'string',
      aliases: [
        'business license',
        'license number',
        'license no',
        'business license number',
        'cin',
      ],
    },
    {
      key: 'incorporationDate',
      label: 'Incorporation Date',
      required: false,
      type: 'string',
      aliases: [
        'incorporation date',
        'date of incorporation',
        'founded',
        'established date',
        'registration date',
      ],
    },
    {
      key: 'natureOfBusiness',
      label: 'Nature of Business',
      required: false,
      type: 'enum',
      enumValues: [
        'Manufacturing',
        'Trading',
        'Services',
        'IT/Software',
        'FMCG',
        'Healthcare',
        'Education',
        'Financial Services',
        'Construction',
        'Logistics',
        'Hospitality',
        'Other',
      ],
      aliases: ['nature of business', 'business nature', 'industry', 'sector', 'business sector'],
    },
    {
      key: 'taxRegistrationNumber',
      label: 'Tax Registration Number',
      required: false,
      type: 'string',
      aliases: [
        'tax registration number',
        'gstin',
        'gst number',
        'vat number',
        'tax id',
        'tax registration',
      ],
    },
    {
      key: 'panNumber',
      label: 'PAN Number',
      required: false,
      type: 'string',
      aliases: ['pan number', 'pan', 'permanent account number', 'pan no', 'pan card'],
    },
    {
      key: 'msmeNumber',
      label: 'MSME Number',
      required: false,
      type: 'string',
      aliases: ['msme number', 'msme', 'udyam number', 'udyam registration', 'msme registration'],
    },
    {
      key: 'registeredAddress',
      label: 'Registered Address',
      required: false,
      type: 'string',
      aliases: [
        'registered address',
        'address',
        'office address',
        'registered office',
        'business address',
      ],
    },
    {
      key: 'city',
      label: 'City',
      required: false,
      type: 'string',
      aliases: ['city', 'town', 'city name'],
    },
    {
      key: 'state',
      label: 'State',
      required: false,
      type: 'string',
      aliases: ['state', 'province', 'state name', 'region'],
    },
    {
      key: 'pincode',
      label: 'Pincode',
      required: false,
      type: 'string',
      aliases: ['pincode', 'pin code', 'zip', 'zip code', 'postal code'],
    },
    {
      key: 'bankName',
      label: 'Bank Name',
      required: false,
      type: 'string',
      aliases: ['bank name', 'bank', 'entity bank'],
    },
    {
      key: 'bankAccountNumber',
      label: 'Bank Account Number',
      required: false,
      type: 'string',
      aliases: ['bank account number', 'account number', 'bank acct', 'acct no'],
    },
    {
      key: 'bankIfsc',
      label: 'Bank IFSC',
      required: false,
      type: 'string',
      aliases: ['bank ifsc', 'ifsc', 'ifsc code', 'routing code'],
    },
    {
      key: 'bankBranch',
      label: 'Bank Branch',
      required: false,
      type: 'string',
      aliases: ['bank branch', 'branch', 'branch name'],
    },
    {
      key: 'isActive',
      label: 'Is Active',
      required: false,
      type: 'boolean',
      aliases: ['is active', 'active', 'status', 'enabled'],
      defaultValue: true,
    },
  ],
};

// ---------------------------------------------------------------------------
// Masters with prerequisites
// ---------------------------------------------------------------------------

const state_master: MasterSchema = {
  masterKey: 'state_master',
  displayName: 'State Master',
  description: 'States / provinces keyed to a country.',
  headerSignature: ['state code', 'state name', 'country'],
  primaryCodeField: 'stateCode',
  prerequisites: ['country_master'],
  prerequisiteNote:
    'States reference Country — the Country Master must be populated before states can be uploaded.',
  fields: [
    {
      key: 'stateCode',
      label: 'State Code',
      required: true,
      type: 'string',
      aliases: ['state code', 'statecode', 'code', 'province code', 'state id'],
    },
    {
      key: 'stateName',
      label: 'State Name',
      required: true,
      type: 'string',
      aliases: ['state name', 'statename', 'name', 'province', 'state'],
    },
    {
      key: 'country',
      label: 'Country',
      required: true,
      type: 'string',
      aliases: ['country', 'country name', 'country code', 'nation'],
      foreignKey: { refMaster: 'country_master', refField: 'countryName', strict: false },
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state status', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const employee_master: MasterSchema = {
  masterKey: 'employee_master',
  displayName: 'Employee Master',
  description: 'Employees with department, entity, cost centre and reporting manager.',
  headerSignature: ['emp code', 'employee code', 'reporting manager', 'base entity'],
  primaryCodeField: 'empCode',
  prerequisites: [
    'department_master',
    'entity_master',
    'cost_centre_master',
    'profit_centre_master',
  ],
  prerequisiteNote:
    'Employees reference Department, Entity, Cost Centre and Profit Centre — these must exist before employees can be uploaded.',
  fields: [
    {
      key: 'empCode',
      label: 'Employee Code',
      required: true,
      type: 'string',
      aliases: ['emp code', 'employee code', 'empcode', 'employeeid', 'employee id', 'emp id'],
    },
    {
      key: 'empName',
      label: 'Employee Name',
      required: true,
      type: 'string',
      aliases: ['emp name', 'employee name', 'empname', 'name', 'full name'],
    },
    {
      key: 'email',
      label: 'Email',
      required: true,
      type: 'email',
      aliases: ['email', 'email id', 'official email', 'work email', 'emailid'],
    },
    {
      key: 'department',
      label: 'Department',
      required: true,
      type: 'string',
      aliases: ['department', 'dept', 'department name', 'department code', 'dept name'],
      foreignKey: { refMaster: 'department_master', refField: 'deptName', strict: false },
    },
    {
      key: 'baseEntity',
      label: 'Base Entity',
      required: true,
      type: 'string',
      aliases: ['base entity', 'entity', 'legal entity', 'home entity', 'primary entity'],
      foreignKey: { refMaster: 'entity_master', refField: 'legalName', strict: false },
    },
    {
      key: 'phone',
      label: 'Phone',
      required: false,
      type: 'string',
      aliases: ['phone', 'phone no', 'mobile', 'mobile number', 'contact', 'telephone'],
    },
    {
      key: 'designation',
      label: 'Designation',
      required: false,
      type: 'string',
      aliases: ['designation', 'title', 'job title', 'position', 'role title'],
    },
    {
      key: 'baseLocation',
      label: 'Base Location',
      required: false,
      type: 'string',
      aliases: ['base location', 'location', 'work location', 'office', 'city'],
    },
    {
      key: 'reportingManager',
      label: 'Reporting Manager',
      required: false,
      type: 'string',
      aliases: ['reporting manager', 'manager', 'reports to', 'reportingmanager', 'supervisor'],
    },
    {
      key: 'costCenter',
      label: 'Cost Centre',
      required: false,
      type: 'string',
      aliases: ['cost centre', 'cost center', 'cc', 'cost centre code', 'cost center code'],
      foreignKey: { refMaster: 'cost_centre_master', refField: 'costCentreCode', strict: false },
    },
    {
      key: 'profitCenter',
      label: 'Profit Centre',
      required: false,
      type: 'string',
      aliases: ['profit centre', 'profit center', 'pc', 'profit centre code', 'profit center code'],
      foreignKey: {
        refMaster: 'profit_centre_master',
        refField: 'profitCentreCode',
        strict: false,
      },
    },
    {
      key: 'defaultFunctionalContext',
      label: 'Default Functional Context',
      required: false,
      type: 'string',
      aliases: [
        'default functional context',
        'functional context',
        'default context',
        'context',
        'module',
      ],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'employment status', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const contract_master: MasterSchema = {
  masterKey: 'contract_master',
  displayName: 'Contract Master',
  description: 'Vendor contracts with product, rate, currency and validity window.',
  headerSignature: ['contract id', 'contract start date', 'rate per unit'],
  primaryCodeField: 'contractId',
  prerequisites: ['vendor_master', 'item_master'],
  prerequisiteNote:
    'Contracts reference Vendors and Products — both masters must be populated before contracts can be uploaded.',
  fields: [
    {
      key: 'contractId',
      label: 'Contract ID',
      required: true,
      type: 'string',
      aliases: ['contract id', 'contract no', 'contract number', 'contractid', 'agreement id'],
    },
    {
      key: 'vendor',
      label: 'Vendor',
      required: true,
      type: 'string',
      aliases: ['vendor', 'vendor name', 'vendor code', 'supplier', 'supplier name'],
      foreignKey: { refMaster: 'vendor_master', refField: 'name', strict: false },
    },
    {
      key: 'productId',
      label: 'Product',
      required: true,
      type: 'string',
      aliases: ['product', 'product id', 'product code', 'productid', 'item code'],
      foreignKey: { refMaster: 'item_master', refField: 'itemCode', strict: false },
    },
    {
      key: 'contractStartDate',
      label: 'Contract Start Date',
      required: true,
      type: 'date',
      aliases: ['contract start date', 'start date', 'from date', 'effective from', 'valid from'],
    },
    {
      key: 'contractEndDate',
      label: 'Contract End Date',
      required: true,
      type: 'date',
      aliases: [
        'contract end date',
        'end date',
        'to date',
        'effective to',
        'valid to',
        'expiry date',
      ],
    },
    {
      key: 'ratePerUnit',
      label: 'Rate Per Unit',
      required: true,
      type: 'number',
      aliases: ['rate per unit', 'rate', 'unit rate', 'price', 'unit price', 'rateperunit'],
    },
    {
      key: 'currency',
      label: 'Currency',
      required: true,
      type: 'string',
      aliases: ['currency', 'currency code', 'ccy', 'contract currency'],
      foreignKey: { refMaster: 'currency_master', refField: 'code', strict: false },
    },
    {
      key: 'paymentTerms',
      label: 'Payment Terms',
      required: true,
      type: 'string',
      aliases: ['payment terms', 'payment term', 'terms', 'credit terms', 'pay terms'],
      foreignKey: { refMaster: 'vendor_payment_terms_master', refField: 'code', strict: false },
    },
    {
      key: 'skuId',
      label: 'SKU',
      required: false,
      type: 'string',
      aliases: ['sku', 'sku id', 'sku code', 'internal sku', 'skuid'],
    },
    {
      key: 'leadTime',
      label: 'Lead Time',
      required: false,
      type: 'string',
      aliases: ['lead time', 'leadtime', 'delivery time', 'lead days', 'tat'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive', 'Expired'],
      aliases: ['status', 'active', 'contract status', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const vendor_master: MasterSchema = {
  masterKey: 'vendor_master',
  displayName: 'Vendor Master',
  description: 'Vendors / suppliers with tax identifiers, category, and payment terms.',
  headerSignature: ['vendor code', 'vendor name', 'gstin', 'pan'],
  primaryCodeField: 'code',
  prerequisites: ['entity_master', 'vendor_payment_terms_master'],
  prerequisiteNote:
    'Vendors reference Entity (for multi-entity scoping) and Payment Terms — both should exist before vendor upload.',
  fields: [
    {
      key: 'code',
      label: 'Vendor Code',
      required: true,
      type: 'string',
      aliases: ['vendor code', 'vendorcode', 'code', 'vendor id', 'supplier code'],
    },
    {
      key: 'name',
      label: 'Vendor Name',
      required: true,
      type: 'string',
      aliases: ['vendor name', 'name', 'vendorname', 'supplier name', 'trade name'],
    },
    {
      key: 'legalName',
      label: 'Legal Name',
      required: true,
      type: 'string',
      aliases: ['legal name', 'legalname', 'registered name', 'company name', 'vendor legal name'],
    },
    {
      key: 'vendorType',
      label: 'Vendor Type',
      required: true,
      type: 'enum',
      enumValues: ['Domestic', 'Import'],
      aliases: ['vendor type', 'type', 'vendortype', 'supplier type'],
      defaultValue: 'Domestic',
    },
    {
      key: 'paymentTerms',
      label: 'Payment Terms',
      required: true,
      type: 'string',
      aliases: ['payment terms', 'payment term', 'terms', 'credit terms', 'pay terms'],
      foreignKey: { refMaster: 'vendor_payment_terms_master', refField: 'code', strict: false },
    },
    {
      key: 'pan',
      label: 'PAN',
      required: false,
      type: 'string',
      aliases: ['pan', 'pan number', 'pan no', 'pancard', 'tax id'],
    },
    {
      key: 'gstin',
      label: 'GSTIN',
      required: false,
      type: 'string',
      aliases: ['gstin', 'gst number', 'gst no', 'gst id', 'gstin number'],
    },
    {
      key: 'email',
      label: 'Email',
      required: false,
      type: 'email',
      aliases: ['email', 'email id', 'contact email', 'vendor email', 'emailid'],
    },
    {
      key: 'phone',
      label: 'Phone',
      required: false,
      type: 'string',
      aliases: ['phone', 'phone no', 'mobile', 'contact', 'telephone', 'contact number'],
    },
    {
      key: 'category',
      label: 'Category',
      required: false,
      type: 'string',
      aliases: ['category', 'vendor category', 'cat', 'classification', 'business category'],
    },
    {
      key: 'creditDays',
      label: 'Credit Days',
      required: false,
      type: 'integer',
      aliases: ['credit days', 'creditdays', 'payment days', 'net days', 'credit period'],
    },
    {
      key: 'msmeRegistered',
      label: 'MSME Registered',
      required: false,
      type: 'boolean',
      aliases: ['msme registered', 'msme', 'is msme', 'msmeregistered', 'ssi registered'],
      defaultValue: false,
    },
    {
      key: 'msmeNumber',
      label: 'MSME Number',
      required: false,
      type: 'string',
      aliases: ['msme number', 'msme no', 'udyam number', 'udyam', 'msme id'],
    },
    {
      key: 'msmeCategory',
      label: 'MSME Category',
      required: false,
      type: 'enum',
      enumValues: ['Micro', 'Small', 'Medium'],
      aliases: ['msme category', 'msme type', 'msmecategory', 'enterprise type'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive', 'Blocked'],
      aliases: ['status', 'active', 'vendor status', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

// TODO: Account Code Master has no dedicated master-screen component; this
// schema is derived from the AccountCodeMaster interface in MasterDataContext.
// Expand when a full Account Code / Chart of Accounts screen is introduced.
const account_code_master: MasterSchema = {
  masterKey: 'account_code_master',
  displayName: 'Account Code Master',
  description: 'Chart of accounts — GL accounts with type, sub-type and hierarchy.',
  headerSignature: ['account code', 'account type', 'account sub type'],
  primaryCodeField: 'code',
  prerequisites: [],
  fields: [
    {
      key: 'code',
      label: 'Account Code',
      required: true,
      type: 'string',
      aliases: ['account code', 'gl code', 'code', 'accountcode', 'ledger code'],
    },
    {
      key: 'name',
      label: 'Account Name',
      required: true,
      type: 'string',
      aliases: ['account name', 'name', 'gl name', 'ledger name', 'accountname'],
    },
    {
      key: 'accountType',
      label: 'Account Type',
      required: true,
      type: 'enum',
      enumValues: ['Asset', 'Liability', 'Equity', 'Revenue', 'Expense'],
      aliases: ['account type', 'type', 'accounttype', 'gl type', 'category'],
    },
    {
      key: 'accountSubType',
      label: 'Account Sub Type',
      required: false,
      type: 'string',
      aliases: ['account sub type', 'sub type', 'subtype', 'account subtype', 'gl sub type'],
    },
    {
      key: 'level',
      label: 'Level',
      required: false,
      type: 'integer',
      aliases: ['level', 'hierarchy level', 'tier', 'depth'],
      defaultValue: 1,
    },
    {
      key: 'parentCode',
      label: 'Parent Account Code',
      required: false,
      type: 'string',
      aliases: ['parent code', 'parent account', 'parent', 'parent account code', 'parentcode'],
    },
    {
      key: 'requiresCostCentre',
      label: 'Requires Cost Centre',
      required: false,
      type: 'boolean',
      aliases: [
        'requires cost centre',
        'requires cost center',
        'needs cost centre',
        'cc required',
        'requirescostcentre',
      ],
      defaultValue: false,
    },
    {
      key: 'requiresProject',
      label: 'Requires Project',
      required: false,
      type: 'boolean',
      aliases: ['requires project', 'needs project', 'project required', 'requiresproject'],
      defaultValue: false,
    },
    {
      key: 'isActive',
      label: 'Is Active',
      required: false,
      type: 'boolean',
      aliases: ['is active', 'active', 'status', 'enabled'],
      defaultValue: true,
    },
  ],
};

// TODO: Bank Master has no dedicated master-screen component; this schema is
// derived from the BankMaster interface in MasterDataContext. Expand when a
// full Bank Master screen is introduced.
const bank_master: MasterSchema = {
  masterKey: 'bank_master',
  displayName: 'Bank Master',
  description: 'Bank accounts used for entity payables / receivables.',
  headerSignature: ['bank name', 'ifsc code', 'account number'],
  primaryCodeField: 'accountNumber',
  prerequisites: ['entity_master'],
  prerequisiteNote:
    'Bank accounts are scoped to a legal entity — the Entity Master must be populated first.',
  fields: [
    {
      key: 'bankName',
      label: 'Bank Name',
      required: true,
      type: 'string',
      aliases: ['bank name', 'bank', 'bankname', 'institution', 'bank institution'],
    },
    {
      key: 'accountNumber',
      label: 'Account Number',
      required: true,
      type: 'string',
      aliases: ['account number', 'account no', 'acct number', 'accountnumber', 'a c no'],
    },
    {
      key: 'ifscCode',
      label: 'IFSC Code',
      required: true,
      type: 'string',
      aliases: ['ifsc code', 'ifsc', 'ifsccode', 'routing code', 'swift code'],
    },
    {
      key: 'accountName',
      label: 'Account Name',
      required: true,
      type: 'string',
      aliases: ['account name', 'acct name', 'account holder', 'accountname', 'beneficiary name'],
    },
    {
      key: 'entityId',
      label: 'Entity',
      required: true,
      type: 'string',
      aliases: ['entity', 'entity id', 'entity code', 'legal entity', 'entityid'],
      foreignKey: { refMaster: 'entity_master', refField: 'code', strict: false },
    },
    {
      key: 'branchName',
      label: 'Branch Name',
      required: false,
      type: 'string',
      aliases: ['branch name', 'branch', 'branchname', 'bank branch'],
    },
    {
      key: 'accountType',
      label: 'Account Type',
      required: false,
      type: 'enum',
      enumValues: ['Current', 'Savings', 'OD'],
      aliases: ['account type', 'type', 'accounttype', 'acct type'],
      defaultValue: 'Current',
    },
    {
      key: 'currency',
      label: 'Currency',
      required: false,
      type: 'string',
      aliases: ['currency', 'currency code', 'ccy', 'account currency'],
      foreignKey: { refMaster: 'currency_master', refField: 'code', strict: false },
    },
    {
      key: 'isPrimary',
      label: 'Is Primary',
      required: false,
      type: 'boolean',
      aliases: ['is primary', 'primary', 'default', 'main', 'isprimary'],
      defaultValue: false,
    },
    {
      key: 'isActive',
      label: 'Is Active',
      required: false,
      type: 'boolean',
      aliases: ['is active', 'active', 'status', 'enabled'],
      defaultValue: true,
    },
  ],
};

const user_master: MasterSchema = {
  masterKey: 'user_master',
  displayName: 'User Master',
  description: 'Application users linked to an employee with entity / role access.',
  headerSignature: ['user code', 'username', 'employee id', 'login method'],
  primaryCodeField: 'userCode',
  prerequisites: ['employee_master', 'roles_master', 'entity_master'],
  prerequisiteNote:
    'Users link to Employees, Roles and Entities — these three masters must be populated before users can be uploaded.',
  fields: [
    {
      key: 'userCode',
      label: 'User Code',
      required: true,
      type: 'string',
      aliases: ['user code', 'usercode', 'code', 'user id', 'userid'],
    },
    {
      key: 'employeeId',
      label: 'Employee',
      required: true,
      type: 'string',
      aliases: ['employee id', 'employee code', 'emp code', 'emp id', 'employeeid', 'employee'],
      foreignKey: { refMaster: 'employee_master', refField: 'empCode', strict: false },
    },
    {
      key: 'name',
      label: 'Full Name',
      required: true,
      type: 'string',
      aliases: ['name', 'full name', 'user name', 'display name'],
    },
    {
      key: 'email',
      label: 'Email',
      required: true,
      type: 'email',
      aliases: ['email', 'email id', 'official email', 'work email', 'emailid'],
    },
    {
      key: 'username',
      label: 'Username',
      required: true,
      type: 'string',
      aliases: ['username', 'login', 'login id', 'user login', 'account name'],
    },
    {
      key: 'defaultEntityId',
      label: 'Default Entity',
      required: true,
      type: 'string',
      aliases: ['default entity', 'default entity id', 'entity', 'primary entity', 'home entity'],
      foreignKey: { refMaster: 'entity_master', refField: 'code', strict: false },
    },
    {
      key: 'userType',
      label: 'User Type',
      required: false,
      type: 'string',
      aliases: ['user type', 'type', 'usertype', 'account type'],
      defaultValue: 'Employee',
    },
    {
      key: 'loginMethod',
      label: 'Login Method',
      required: false,
      type: 'enum',
      enumValues: ['Password', 'SSO', 'OIDC'],
      aliases: ['login method', 'loginmethod', 'auth method', 'authentication', 'auth type'],
      defaultValue: 'Password',
    },
    {
      key: 'locked',
      label: 'Locked',
      required: false,
      type: 'boolean',
      aliases: ['locked', 'is locked', 'account locked', 'islocked'],
      defaultValue: false,
    },
    {
      key: 'passwordResetRequired',
      label: 'Password Reset Required',
      required: false,
      type: 'boolean',
      aliases: [
        'password reset required',
        'reset password',
        'force reset',
        'passwordresetrequired',
        'must change password',
      ],
      defaultValue: false,
    },
    {
      key: 'accessExpiryDate',
      label: 'Access Expiry Date',
      required: false,
      type: 'date',
      aliases: [
        'access expiry date',
        'expiry date',
        'expires on',
        'valid till',
        'accessexpirydate',
      ],
    },
    {
      key: 'remarks',
      label: 'Remarks',
      required: false,
      type: 'string',
      aliases: ['remarks', 'notes', 'comments', 'description'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive', 'Pending Approval'],
      aliases: ['status', 'active', 'user status', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const exchange_rate_master: MasterSchema = {
  masterKey: 'exchange_rate_master',
  displayName: 'Exchange Rate Master',
  description: 'Currency exchange rates with rate type and effective date.',
  headerSignature: ['from currency', 'to currency', 'exchange rate', 'effective from'],
  primaryCodeField: 'fromCurrency',
  prerequisites: ['currency_master'],
  prerequisiteNote:
    'Exchange rates reference Currency — the Currency Master must be populated before rates can be uploaded.',
  fields: [
    {
      key: 'fromCurrency',
      label: 'From Currency',
      required: true,
      type: 'string',
      aliases: ['from currency', 'fromcurrency', 'source currency', 'base currency', 'from ccy'],
      foreignKey: { refMaster: 'currency_master', refField: 'code', strict: false },
    },
    {
      key: 'toCurrency',
      label: 'To Currency',
      required: true,
      type: 'string',
      aliases: ['to currency', 'tocurrency', 'target currency', 'quote currency', 'to ccy'],
      foreignKey: { refMaster: 'currency_master', refField: 'code', strict: false },
    },
    {
      key: 'exchangeRate',
      label: 'Exchange Rate',
      required: true,
      type: 'number',
      aliases: ['exchange rate', 'rate', 'fx rate', 'conversion rate', 'exchangerate'],
    },
    {
      key: 'rateType',
      label: 'Rate Type',
      required: true,
      type: 'string',
      aliases: ['rate type', 'ratetype', 'type', 'fx type', 'rate category'],
      defaultValue: 'Spot',
    },
    {
      key: 'effectiveFromDate',
      label: 'Effective From Date',
      required: true,
      type: 'date',
      aliases: ['effective from date', 'effective from', 'from date', 'valid from', 'start date'],
    },
    {
      key: 'isActive',
      label: 'Is Active',
      required: false,
      type: 'boolean',
      aliases: ['is active', 'active', 'status', 'enabled'],
      defaultValue: true,
    },
  ],
};

const tds_section_master: MasterSchema = {
  masterKey: 'tds_section_master' as MasterKey,
  displayName: 'TDS Section Master',
  description:
    'TDS/TCS sections with applicable rates for individuals, companies and no-TAN scenarios.',
  headerSignature: ['section code', 'section name', 'rate individual'],
  primaryCodeField: 'sectionCode',
  prerequisites: [],
  fields: [
    {
      key: 'sectionCode',
      label: 'Section Code',
      required: true,
      type: 'string',
      aliases: ['section code', 'sectioncode', 'section', 'tds section', 'code'],
    },
    {
      key: 'sectionName',
      label: 'Section Name',
      required: true,
      type: 'string',
      aliases: ['section name', 'sectionname', 'name', 'tds section name'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      aliases: ['description', 'desc', 'details', 'remarks'],
    },
    {
      key: 'rateIndividual',
      label: 'Rate - Individual (%)',
      required: true,
      type: 'number',
      aliases: ['rate individual', 'individual rate', 'rate ind', 'individual %'],
    },
    {
      key: 'rateCompany',
      label: 'Rate - Company (%)',
      required: true,
      type: 'number',
      aliases: ['rate company', 'company rate', 'rate corp', 'company %'],
    },
    {
      key: 'rateNoTan',
      label: 'Rate - No TAN (%)',
      required: false,
      type: 'number',
      aliases: ['rate no tan', 'no tan rate', 'higher rate', 'default rate'],
      defaultValue: 20,
    },
    {
      key: 'thresholdAmount',
      label: 'Threshold Amount',
      required: false,
      type: 'number',
      aliases: ['threshold amount', 'threshold', 'limit', 'annual threshold', 'exemption limit'],
    },
    {
      key: 'applicableTo',
      label: 'Applicable To',
      required: false,
      type: 'string',
      aliases: ['applicable to', 'applicability', 'applies to', 'category', 'nature of payment'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const location_master: MasterSchema = {
  masterKey: 'location_master' as MasterKey,
  displayName: 'Location Master',
  description: 'Physical locations — warehouses, stores, offices, and factories.',
  headerSignature: ['location code', 'location name', 'location type'],
  primaryCodeField: 'locationCode',
  prerequisites: ['entity_master'],
  prerequisiteNote: 'Locations reference Entity — the Entity Master should be populated first.',
  fields: [
    {
      key: 'locationCode',
      label: 'Location Code',
      required: true,
      type: 'string',
      aliases: ['location code', 'locationcode', 'code', 'loc code', 'site code'],
    },
    {
      key: 'locationName',
      label: 'Location Name',
      required: true,
      type: 'string',
      aliases: ['location name', 'locationname', 'name', 'loc name', 'site name'],
    },
    {
      key: 'locationType',
      label: 'Location Type',
      required: true,
      type: 'enum',
      enumValues: ['Warehouse', 'Store', 'Office', 'Factory'],
      aliases: ['location type', 'type', 'loc type', 'site type', 'facility type'],
    },
    {
      key: 'address',
      label: 'Address',
      required: false,
      type: 'string',
      aliases: ['address', 'street address', 'addr', 'location address'],
    },
    {
      key: 'city',
      label: 'City',
      required: true,
      type: 'string',
      aliases: ['city', 'town', 'district'],
    },
    {
      key: 'state',
      label: 'State',
      required: true,
      type: 'string',
      aliases: ['state', 'province', 'region'],
    },
    {
      key: 'pincode',
      label: 'Pincode',
      required: false,
      type: 'string',
      aliases: ['pincode', 'pin code', 'postal code', 'zip code', 'zip'],
    },
    {
      key: 'parentEntity',
      label: 'Parent Entity',
      required: false,
      type: 'string',
      aliases: ['parent entity', 'entity', 'legal entity', 'company'],
      foreignKey: { refMaster: 'entity_master', refField: 'name', strict: false },
    },
    {
      key: 'contactPerson',
      label: 'Contact Person',
      required: false,
      type: 'string',
      aliases: ['contact person', 'contact name', 'person', 'poc'],
    },
    {
      key: 'contactPhone',
      label: 'Contact Phone',
      required: false,
      type: 'string',
      aliases: ['contact phone', 'phone', 'mobile', 'telephone', 'contact number'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state status', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

const gl_code_master: MasterSchema = {
  masterKey: 'gl_code_master' as MasterKey,
  displayName: 'GL Code Master',
  description: 'General ledger codes for entity-level accounting.',
  headerSignature: ['gl code', 'gl description', 'gl type'],
  primaryCodeField: 'glCode',
  prerequisites: [],
  fields: [
    {
      key: 'glCode',
      label: 'GL Code',
      required: true,
      type: 'string',
      aliases: ['gl code', 'glcode', 'gl account', 'ledger code', 'account code', 'code'],
    },
    {
      key: 'glDescription',
      label: 'GL Description',
      required: true,
      type: 'string',
      aliases: ['gl description', 'gl name', 'description', 'name', 'gl desc', 'account name'],
    },
    {
      key: 'glType',
      label: 'GL Type',
      required: false,
      type: 'enum',
      enumValues: [
        'expense',
        'asset',
        'liability',
        'revenue',
        'cogs',
        'tax',
        'stock',
        'bank',
        'other',
      ],
      aliases: ['gl type', 'type', 'account type', 'gl category'],
      defaultValue: 'expense',
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      aliases: ['status', 'active', 'state', 'is active'],
      defaultValue: 'Active',
    },
  ],
};

// ---------------------------------------------------------------------------
// Final registry
// ---------------------------------------------------------------------------

export const masterSchemaRegistry: MasterSchemaRegistry = {
  category_master,
  country_master,
  state_master,
  department_master,
  tax_code_master,
  item_category_master,
  vendor_payment_terms_master,
  item_master,
  uom_master,
  debit_note_reason_master,
  cost_centre_master,
  profit_centre_master,
  employee_master,
  contract_master,
  vendor_master,
  account_code_master,
  bank_master,
  roles_master,
  user_master,
  currency_master,
  entity_master,
  exchange_rate_master,
  tds_section_master,
  location_master,
  gl_code_master,
};

/** Convenience: list of all known master keys in registration order. */
export const masterSchemaKeys: MasterKey[] = Object.keys(masterSchemaRegistry) as MasterKey[];

/** Look up a schema by key, returning undefined if not registered. */
export function getMasterSchema(key: MasterKey): MasterSchema | undefined {
  return masterSchemaRegistry[key];
}
