/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pqpaefoghczmatthavbs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxcGFlZm9naGN6bWF0dGhhdmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMjI3OTQsImV4cCI6MjA5MDY5ODc5NH0.K-WeUPYTEcChCAdinUS-XZW1XdfwhCxze5sTVCc5WM4"
